### ISSUE TITLE
Switch to Maven?

### ISSUE THREAD

**Issue by ctrueden** [OmegaProject/Omega#1]
You got the Maven build working during the hackathon, right? It would be great to switch to that!

**Comment by Akramhar** [comment]
Yes I will synchronize all the repos next week.

**Comment by ctrueden** [comment]
:+1:

**Comment by Akramhar** [comment]
I updated the main project and the 2 commons projects I created during the hackaton, now I have to decided where to upload the first version of the plugin I did.

**Comment by Akramhar** [comment]
I uploaded the plugin here:
https://github.com/OmegaProject/ImageJPlugins
As previously said everything is in a very early stage ;)

**Comment by ctrueden** [comment]
Thanks!
