### ISSUE TITLE
ParticleDetector MOSAIC crashes when launching "Execute Queue" for second time

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#103]
When a first execution has terminated, attempting to launch a second execution on the queue triggers the program to crash.
Reproduced a number of times on Win

**Comment by strambc** [comment]
Has to check also on Mac

**Comment by strambc** [comment]
Same bug on Mac.

**Comment by strambc** [comment]
[Log_general.txt](https://github.com/OmegaProject/Omega/files/576613/Log_general.txt)

**Comment by Akramhar** [comment]
Should be solved, need to be tested
