### ISSUE TITLE
ParticleLinking, SNREstimator and TrajectoryManager plugins do not have "File" and "View" menus when undocked

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#109]
When the ParticleLinking, SNREstimator and TrajectoryManager plugin windows are undocked they loose the File and View menus.
Any reason?
For consistency all plugins should have the same functionality/appearance

**Comment by strambc** [comment]
Related to #106

**Comment by Akramhar** [comment]
![test1](https://cloud.githubusercontent.com/assets/3996749/21785537/f309f50c-d68d-11e6-987d-68c78ed182b1.png)
It seems to be working! Could you elaborate more?

**Comment by Akramhar** [comment]
We need a better analysis of this problem to be able to replicate it as needed

**Comment by strambc** [comment]
Closed this issue and left the newer one instead.
#239
