### ISSUE TITLE
OmegaBrowser Times Analyzed counter does not work as it should

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#112]
Related to #110
Times Analyzed counts all analysis runs down the entire tree while it should just count the times the data produced by one run is used as input for the subsequent chain in pipeline.

For example when an image has been subjected to 1 PD and 1 PL the counter should say:
-Image: times analyzed 1
-PD: time analyzed 1
-PL: time analyzed 1 (= the default RE-LINKING RUN)
-TE: times analyzed 1 (= the default SEGMENTATION RUN)
-TS: times analyzed 0

Instead it says:
-Image: times analyzed 4
-PD: time analyzed 3
-PL: time analyzed 2 
-TE: times analyzed 1
-TS: times analyzed 0

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
As far as Image and Analysis the counter now works.
Instead it does not work as far as the 
PROJECT and the DATASET are conerned.
Opened a new ISSUE about Project and Dataset
