### ISSUE TITLE
OmegaBrowser clarify difference between clicking check box and simpling selecting

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#116]
The difference between checking the box and simply selecting by clicking on the name of the item is not clear and EXTREMELY CONFUSING.
The confusion is compounded by what appears to be a Java interface glitch connected to checking/unchecking a box.

This is related to #14 and #117

**Comment by Akramhar** [comment]
This should be resolved between omega-0.34 and omega-0.35

**Comment by strambc** [comment]
Most problems are solved. A new issue was open for the remaining ones.
 #290
