### ISSUE TITLE
OmegaBrowser unchecking PL runs does not update on SidePanel

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#117]
When a PL run is unchecked it not necessarily is removed from SidePanel.
For example in one instance, 8 runs were present and checked --> 7 were unchecked --> the SidePanel continues showing three of them. 
In addition, when three were reloaded from scratch, three check boxes appear as checked (even though only one had been left originally).

This is connected with #14 and #116

**Comment by Akramhar** [comment]
This seems to be solved in omega-0.34 or omega-0.35

**Comment by strambc** [comment]
Most problems are solved. A new issue was open for the remaining ones.
 #290
