### ISSUE TITLE
TrackEditor timepoint display in confirm split window is wrong

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#120]
See attached screen shots. 
Upon splitting a trajectory, the confirm window displayed the wrong time point: i.e. time 

![trackeditor split_phase 1](https://cloud.githubusercontent.com/assets/4050585/19056673/afdb953e-8998-11e6-83fd-06f34c30a4b7.png)
![trackeditor split_phase 2](https://cloud.githubusercontent.com/assets/4050585/19056674/afdd44a6-8998-11e6-980b-ff91621f7493.png)

point 40 instead of 49

**Comment by Akramhar** [comment]
This should be solved in omega-0.34
