### ISSUE TITLE
SidePanel image + TrajectoryBrowser clicking to select an item is often not working

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#121]
One often finds oneself often attempting to select a trajectory on the image or on the TB display in vain.
Repeated clicks do not amount to a selection.
It is really frustrating

**Comment by strambc** [comment]
Same thing when attempting to open contextual menus on both TB and SidePanel

**Comment by Akramhar** [comment]
As we said: test it again while checking for errors in the logs

**Comment by strambc** [comment]
This was closed and replaced by #228
