### ISSUE TITLE
SidePanel when assigning a new color to an edited trajectory all other disappear

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#122]
When assigning a new color to an edited trajectory all other disappear on image SidePanel viewer

**Comment by strambc** [comment]
What happens is that somehow the selection of "Unsaved relinking" is lost and one has to select it again on the Select Editing Run in order for it to show again. It is very disruptive and annoying.

**Comment by Akramhar** [comment]
I close this issue because we have #245 now to discuss the topic
