### ISSUE TITLE
Segmented Tracks are not displayed in SidePanel

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#126]
--> "Segmented Tracks" are not displayed in over Image on SidePanel: only the spots are displayed, not the trajectories. Impossible to select trajectories?
--> This applies also with TrackSegmentation results, which are not displayed when "Segmented Tracks" is selected in SidePanel.

**Comment by Akramhar** [comment]
Problem 1: should be solved, need to be tested
Problem 2: I don't understand what the suggested problem is in this case
