### ISSUE TITLE
 TrajectorySegmentation issue with colors and names

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#127]
1) In the Trajectory Segmentaion window:
Segmentation results are not displayed in the browser at all and the original trajectory colors are retained.
VERY CONFUSING. Not clear whether anything happened at all.

2) in the Tracking Measures window
When trajectories are segmented the prevalent color is the MOTION TYPE COLOR.
Also all segments retain the original Trajectory name, with no indication of the segment name.
Both of these elements are confusing.

---Segments have to be assigned a name that makes it clear what segment they are and whose trajectory they come from
---Segment color has to be somehow integrated with the original trajectory color.

The solution to both of these problems has to be consistent.

**Comment by strambc** [comment]
Discuss with Alex about possible solutions

**Comment by strambc** [comment]
I have repeated the same workflow and obtained a very different result: this time the segmentation results are not displayed at all and the original trajectory colors are retained.
VERY CONFUSING.
NOT CLEAR WHAT THE EXPECTED BEHAVIOR IS SUPPOSED TO BE.

**Comment by strambc** [comment]
Had a discussion with Alex.
Decided that Trajectories will have the following behavior on the Trajectory Browser:

1. When they are created they will be displayed with the Trajectory color as it is now.
2. If not segmented, this will be the only color utilized across all Browser/Selector windows.
3. When trajectories are segmented an additional color will be added to the SQUARE box containing each spot of the trajectory.

After discussing with Alex it was decided that the best solution is to display the motion type color code as corner triangles as shown in the attached image.

**Comment by strambc** [comment]
![test](https://cloud.githubusercontent.com/assets/4050585/19403915/48acf0bc-9238-11e6-8365-7a13de62846f.jpg)

**Comment by strambc** [comment]
Point 1 is not critical

**Comment by Akramhar** [comment]
should be solved, need to be tested

**Comment by strambc** [comment]
Closed but new issue started regarding cut off of trajectory/sements names in TB
#167
