### ISSUE TITLE
 TrajectorySegmentation segmentation results not displayed in TM window

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#130]
1) Track segmentation results are not updated in the Segmentation tab of the TM window when different results are displayed.
2) In addition they are not also displayed in the Browser tab.

**Comment by strambc** [comment]
Connected with #126

**Comment by strambc** [comment]
Point 2) is not critical

**Comment by Akramhar** [comment]
should be solved, need to be tested
