### ISSUE TITLE
 TrajectorySegmentation issue with saving the segmentation of multiple trajectories in a single run

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#131]
When one wants to segment multiple trajectories and save them all in a single run, it appears to be impossible at the time being.
This has to be modified.
It is common to have to segment a single trajectory, segment it and then decide to segment another one.
In that case the second trajectory is saved in a second run.

**Comment by Akramhar** [comment]
I don't understand this problem.
One can select track-A, segment it, then select track-B, segment it and then save.
Or one can select track-A, select track-B, segment track-A, segment track-B and then save.
