### ISSUE TITLE
Omega Tracking Measures Run tab issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#132]
The RUN button in the Run tab in Tracking Measures is not responsive.
When pressed nothing happens. The log says: "All frames loaded".

This happens in the following cases:

A) A specific Trajectory Segmentation result is selected
1. Individual trajectory (unsegmented) selected
2. Individual segment selected

B) A) Default segmentation run is selected
1. Individual trajectory (unsegmented) selected

**Comment by strambc** [comment]
Draw button in Graph tab is also un-responsive.

**Comment by strambc** [comment]
Happens with:

TMI
TMM
TMV

**Comment by Akramhar** [comment]
Everything seem to be fixed now. Need to be tested extensivly.
The intensity is not going to work in the Detection+Linking setup because of the fact the values have not been update yet.
