### ISSUE TITLE
Omega Tracking Measures>Diffusivity multiple issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#133]
A) Run 
Appears to work:
                   --> Plugin ready
                   --> Diffusivity analysis ended
But...
                  --> "Error enabled" is the default parameter (should be "Error disabled")
                 ---> Despite "Error enabled" the run is allowed to execute and there is no warning. 
                         Display says: "Processing error analysis, trajectory Traj_0 1/498" but it is still
                         possible to select "Error disabled" and relaunch another run.

B) Graph are at least partially displayed...
...But:
2. appears to be very very buggy and does not update display properly.
3. trajectory graph is not displayed at all
4. other graph are displayed in an inconsistent manner
5. progress bar says: "Graph 99.40 completed" or "Graph 0.8 completed"
6. When error analysis is enabled, the phase graph is not displayed. Progress report states: "Graph 33.33 completed."

**Comment by strambc** [comment]
Discuss with Alex to explain better the situation

**Comment by Akramhar** [comment]
need to be retested after the fix
