### ISSUE TITLE
Omega Tracking Measures > Browser does not allow to change color

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#134]
Color assignment is missing from the Trajectory Browser tab of Trajectory Measures Diffusivity.
This is a general issue for all Trajectory Measures windows.
Connected with #127

**Comment by strambc** [comment]
In addition even when colors have been assigned they are not displayed in the TMD browser tab

**Comment by Akramhar** [comment]
Regarding color change in Tracking Measures
TMD (as TMM TMV and TMI) have a browser that displays segments, not tracks.
So the question is: should we allow to change tracks color from a segment browser? 
Conceptually I think this would be wrong. In this browser we should interact only with segments.

**Comment by Akramhar** [comment]
Regarding color display:
Should be working now, needs to be tested

**Comment by Akramhar** [comment]
Color change should work now

**Comment by strambc** [comment]
Works
