### ISSUE TITLE
Trajectory Manager crash while selecting a trajectory on the browser 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#136]
Happened three in a row.
1) First time
Loaded single image
PD
PL
Open TE --> clicked on Trajectory --> Crash

2) Second time (Right after):
Loaded single image
PD
PL
Open TE --> clicked on Trajectory --> changed color
Open TS --> clicked on Trajectory --> crash

3) Tried a third time (a few minutes later):
Loaded single image
PD
PL
Open TE --> clicked on Trajectory --> changed color
Open TS --> clicked on Trajectory --> clicked on Segmentation tab
Move to TE --> clicked on Trajectory --> crash

**Comment by strambc** [comment]
[OmegaLog_Plugin_OMEGATrajectorySegmentation copy.txt](https://github.com/OmegaProject/Omega/files/530215/OmegaLog_Plugin_OMEGATrajectorySegmentation.copy.txt)

**Comment by Akramhar** [comment]
This should be solved, need to be tested
