### ISSUE TITLE
TrajectorySegmentation navigation arrows in Segmentation tab do not work

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#138]
When selecting more than one trajectory and attempting to navigate between them using the bottom arrows in the Segmentation tab, the trajectory display does not refresh.

**Comment by strambc** [comment]
Related to #179

**Comment by Akramhar** [comment]
the "navigation arrows" has the only purpose to allow you to rename trajectories.
in omega-0.26 is going to be visible only in the browser panel.

**Comment by strambc** [comment]
Cool.
That works

On Mar 15, 2017, at 14:48, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


the "navigation arrows" has the only purpose to allow you to rename trajectories.
in omega-0.26 is going to be visible only in the browser panel.
