### ISSUE TITLE
Omega Tracking Measures default tracking measures run do not appear in the selector

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#139]
1. Tracking measures default runs do not appear in the data selector in any of the TM plugins.
2. When a Diffusivity run is performed the results appear in the selector. However, sometimes the same run name is duplicated and when one clicks to select one, all other duplicates are also selected (i.e. a check mark appears next to the name).

**Comment by Akramhar** [comment]
needs to be verified now that i fixed a bug in the production of results
