### ISSUE TITLE
TrackSegmentation connecting segments in Browser

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#141]
When segmented trajectories are displayed in the Browser for either TS and TM plugins they have to follow the following rules:
1. the different segments from each trajectory have to be displayed next to each other
2. the different segments have to be connected on the GUI with a dashed line
3. the group of segments from a single trajectory has to be highlighted with a lighter version of the trajectory color both under the segment group and along the side of the browser (where the names are displayed)

**Comment by strambc** [comment]
In addition:

be careful that order of segments is maintained across all views especially after changing selection or view. 
Currently they get reshuffled

**Comment by Akramhar** [comment]
1) should be solved in omega-0.34
2) considering that ending point of one segment is equal to starting point of the following segment i would find a dashed line very confusing
3) ROI have now 2 colors, the corner color should allow tracks identification in a very easy way.

If some of this problem are still present please create a separate issue for each and close this.

**Comment by strambc** [comment]
Closed this issue.
Remaining items move to --> #274
