### ISSUE TITLE
Omega Tracking Measures: summary graphs needed

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#142]
1. We need summary graphs with associated data similar to the ones displayed in Figure 5c of Gorelik et al. 2014 (see attached link).
2. We need to have summary graph with all trajectories in the dataset plotted from the origin (origin in the center of the graph) as displayed in Figure 5a of the same paper. 
   For this purpose we can use the MOTION CLASSIFICATION plot but show only the x-y plots.
3. We need to have a way of comparing results aggregated by IMAGE and/or by DATASET 

http://www.nature.com/doifinder/10.1038/nprot.2014.131

Point 2 is higher priority than 1 and 3

**Comment by Akramhar** [comment]
we need to talk about this so that I can better understand what do  you mean

**Comment by strambc** [comment]
Point 2 is DONE.
Points 1 and 3 would be great to have

**Comment by Akramhar** [comment]
This issue needs to be separated in 2 different issues: 1 and 3
