### ISSUE TITLE
OmegaTracksImporter GUI label changes

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#153]
Change the following labels in the Omega Tracks Importer window

Title: Omega Track Importer --> Omega Trajectory Importer 

Insert file identifier --> File identifier
TOOLTIP: "Enter a single file name or in case of multiple files to import, enter a regular expression (RegEx) capturing the file name pattern being used.
For example for the following file name: SMSS_MIXED_1.txt
The correct RegEx is: SMSS_MIXED_[\d].txt"
 
Data identifier --> Data type identifier
TOOLTIP: "In case all of your data is contained in a single file, enter the term describing the type of the data you wish to import. Examples are: Particle, Link, Trajectory, Edited Trajectory, Segment etc."

Particle identifier --> Particle line identifier
TOOLTIP: "If available, enter the character that in your file identifies lines containing particle data"

Non-particle identifier --> Comment line identifier
TOOLTIP: "Enter the character which in your file identifies lines containing comments or other non-particle data. These lines will be ignored by the importer. Typical examples include: %, >, /# etc."

Particle separator --> Column separator

Particle data and order --> Data entry names and order

Other tooltips:

Multiple files
TOOLTIP: "Check this box if your data is subdivided in multiple files that contain for example one trajectory per file".

**Comment by Akramhar** [comment]
Should be done, need to be tested

**Comment by strambc** [comment]
The following was not done:
Insert file identifier --> File identifier

The following should be re-done:
Currently (after latest change)
Title: Omega Track Importer --> Omega Data Importer
I do not like DATA importer. 
From our discussion it emerged that it is always Particles or Trajectories
The title should be more specific: for example
--> Omega Particle/Trajectory Data Importer

**Comment by Akramhar** [comment]
Should be done, needs to be solved
