### ISSUE TITLE
OmegaTrackingMeasures all graphs colors should reflect trajectory colors

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#157]
Trajectory colors:

1) Un-Segmented: when motion type name is "UNASSIGNED" segment color has to reflect the global trajectory color

2) Segmented: when motion type name has been assigned, segment color should reflect the segment color

**Comment by Akramhar** [comment]
Should be solved, need to be tested

**Comment by strambc** [comment]
Solved for Motion Type graphs but not for Diffusivity graphs.
Bar graphs and lines are black even though the trajectory color has been assigned to red

**Comment by Akramhar** [comment]
Should be fixed

**Comment by strambc** [comment]
Not sure if bit regarding segments is ok.
The bit regarding trajectories colors in TM Intensity, Mobility, Velocity and Diffusivity works fine
