### ISSUE TITLE
OmegaTrajectoryImporter cannot import second batch of trajectories

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#158]
It appears that once one set of trajectories has been imported a second set cannot be imported

**Comment by Akramhar** [comment]
I just imported 2 times the TRANSPOSED and 1 time the MIXED without any issue.
![image](https://cloud.githubusercontent.com/assets/3996749/23322413/cdfb28f6-fab1-11e6-9b02-a85cb1dc4e20.png)

**Comment by strambc** [comment]
He che te devo d’… dobbiamo farlo insieme

On Feb 24, 2017, at 16:53, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


I just imported 2 times the TRANSPOSED and 1 time the MIXED without any issue.
[image]<https://cloud.githubusercontent.com/assets/3996749/23322413/cdfb28f6-fab1-11e6-9b02-a85cb1dc4e20.png>

**Comment by strambc** [comment]
CI sei possiamo parlare?
Ho anche da dirti un altra cosa
C

On Feb 24, 2017, at 17:23, Strambio, Caterina <Caterina.Strambio@umassmed.edu<mailto:Caterina.Strambio@umassmed.edu>> wrote:

He che te devo d’… dobbiamo farlo insieme

On Feb 24, 2017, at 16:53, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


I just imported 2 times the TRANSPOSED and 1 time the MIXED without any issue.
[image]<https://cloud.githubusercontent.com/assets/3996749/23322413/cdfb28f6-fab1-11e6-9b02-a85cb1dc4e20.png>

**Comment by strambc** [comment]
Resolved
