### ISSUE TITLE
OmegaTrackingMeasures Diffusivity Motion Classification --> graph have problems

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#159]
https://www.dropbox.com/sh/ut0wemrqh58wxxb/AABMmNHIoR-t3aqhN-JNa7LMa?dl=0

Please check the comparison between graphs obtained in 2015 and those produced today.
There are various issues in the graphs including x-y plots which do not show correctly negative x and y values.
However the computed values appear to be correct.

**Comment by Akramhar** [comment]
Should be solved, need to be tested

**Comment by strambc** [comment]
Solved
