### ISSUE TITLE
OmegaDiffusivityMeasures plot for specific artificial trajectory does not display

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#160]
[SMSS_0-7_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/800632/SMSS_0-7_D_0-0100.txt)

The trajectory in attachment would not produce graphs in the Diffusivity Measures plug-in

**Comment by Akramhar** [comment]
This trajectories have negative numbers, they should be shifted to positive

**Comment by Akramhar** [comment]
Should be solved, need to be tested

**Comment by strambc** [comment]
Solved with 2017-02-27_OMEGA_distribution_PreBetaRelease_V0.21
