### ISSUE TITLE
OmegaDiffusivityMeasures of segmented trajectory

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#162]
TRANSPOSED_MIXED_2.txt
[TRANSPOSED_SMSS_MIXED_2.txt](https://github.com/OmegaProject/Omega/files/805346/TRANSPOSED_SMSS_MIXED_2.txt)

When the trajectory is segmented individual segments cannot be selected and Diffusivity --> Motion Type graphs do not display

**Comment by Akramhar** [comment]
Should be solved in release 0.22
