### ISSUE TITLE
OmegaTrajectorySegmentation cannot select segments

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#164]
After trajectory is segmented, individual segments cannot be selected.
Clicking results in selecting and de-selecting the green selection check mark.

**Comment by strambc** [comment]
Noticed that there appears to be a problem with refreshing the screen upon selection.
If one selects in Browser, clicks on another tab and then goes back to Browser now the segments seem selected.
However, the graphs still do not display

**Comment by Akramhar** [comment]
Should be solved in release 0.22

**Comment by strambc** [comment]
Solved in general.
Except the app appeared to crash after a few clicks.
Still something not quite right with selection.
Will close this and open a new issue
