### ISSUE TITLE
TrajectoryBrowser: full names are cut off and display only in part 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#167]
Connected with closed issue #127

In TB the names of trajectories or segments is cut off because of lack of space on the side panel.
Has to be solved with tooltip or sliding window.

**Comment by Akramhar** [comment]
should be fixed with tooltip

**Comment by strambc** [comment]
NO tooltip on the TMDiffusivity Browser

**Comment by Akramhar** [comment]
should be fixed in omega-0.24

**Comment by strambc** [comment]
Works
