### ISSUE TITLE
OmegaTrajectorySegmentation trajectory view in Segmentation tab shifts and re-scale issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#168]
1) When the trajectory is zoomed in, and one clicks on the top bar to click on motion type, select Start or End or when one clicks on a spot within the segmentation space, the windows shifts sideways hiding the trajectory from view.
THIS IS SPORADIC but have not identified a specific trigger case.
VERY ANNOYING.

2) When a segmentation dataset is loaded or reloaded it is re-set to 1:1 scale even if the user had left it in Scale to Fit mode. 
The persistence of zoomed in view or other view user selection is a problem in general.

**Comment by strambc** [comment]
--Same problem happens also when toggling between show data selector/hide data selector

**Comment by strambc** [comment]
-very annoying that whenever a different segmentation run is selected the view goes back to 1:1 instead of maintaining previously selected re-scaled view

**Comment by Akramhar** [comment]
should be solved in omega-0.26
