### ISSUE TITLE
OmegaTrackingMeasures local intensity measures are missing

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#169]
Local intensity measures such as 
Peak intensity
Centroid Intenisty
Local BKG
Local Noise
are all missing.
Do they require SNREstimator run?
Should not...

Also if LOCAL are missing then plotting by timepoint should be missing from options of possible graphs.

**Comment by Akramhar** [comment]
If you are using imported trajectories there is no intensity to work with.
Peak and Centroid are the only one that dont require snr

**Comment by strambc** [comment]
I am pretty sure I did this with trajectories from Images.
Have to double check before closing

**Comment by strambc** [comment]
This is still happening. NOT SOLVED

**Comment by strambc** [comment]
Make sure all Intensity Measures populate the TMI graph menus regardless of whether or not the SNR was run.
If SNR was not run, then the graphs should appear blank when selected by user

**Comment by Akramhar** [comment]
should be solved in omega-0.29
