### ISSUE TITLE
Omega v023 general: repeated crashed different scenarios

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#170]
Something is not right.
There are repeated crashes with different scenarios.

**1) CASE 1**

1. Imported 
[TRANSPOSED_SMSS_MIXED_4_short.txt](https://github.com/OmegaProject/Omega/files/822549/TRANSPOSED_SMSS_MIXED_4_short.txt)
2. segmented
3. saved segmentation
4. TMD browser displays the four segments correctly
5. selected all four
6. run analysis 
7. Complete set not dispalyed, only Trajectory plot, MSS and scatter plots available individually
8. went back to Browser, only one set of results available
9. not able to move back to Default Segmentation run 
IN GENERAL appears to be same behavior as for v022
Restarted application

**2) CASE 2 - OVERT CRASH**
1. Imported 
[TRANSPOSED_SMSS_MIXED_4_short.txt](https://github.com/OmegaProject/Omega/files/822549/TRANSPOSED_SMSS_MIXED_4_short.txt)
2. crash
[crash_readme.txt](https://github.com/OmegaProject/Omega/files/822558/crash_readme.txt)

**3) CASE 3 - Trajectory imported as series of split particles**
1. Imported 
[TRANSPOSED_SMSS_MIXED_4_short.txt](https://github.com/OmegaProject/Omega/files/822549/TRANSPOSED_SMSS_MIXED_4_short.txt)
2. went to TM-TS Browser, Trajectory appears as a series of disjointed particles

**Comment by strambc** [comment]
Log is empty in all cases.

**Comment by Akramhar** [comment]
should be fixed in omega-0.24
