### ISSUE TITLE
OmegaSegmentation: Start = position 2, End = N+2

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#178]
When selecting Start in a trajectory I noticed that the Selector indicates position 2 and that when selecting End the selector indicates position 436 (N=434).
There appears to still be a problem with the indexes.

**Comment by strambc** [comment]
In the Browser the trajectory is displayed correctly: 1 --> 435

**Comment by strambc** [comment]
Tested it with the following trajectories:

[TRANSPOSED_SMSS_0-1_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838704/TRANSPOSED_SMSS_0-1_D_0-0100.txt)
[TRANSPOSED_SMSS_0-3_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838702/TRANSPOSED_SMSS_0-3_D_0-0100.txt)
[TRANSPOSED_SMSS_0-5_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838701/TRANSPOSED_SMSS_0-5_D_0-0100.txt)
[TRANSPOSED_SMSS_0-7_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838700/TRANSPOSED_SMSS_0-7_D_0-0100.txt)
[TRANSPOSED_SMSS_1-0_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838703/TRANSPOSED_SMSS_1-0_D_0-0100.txt)
[TRANSPOSED_SMSS_MIXED_1.txt](https://github.com/OmegaProject/Omega/files/838705/TRANSPOSED_SMSS_MIXED_1.txt)
[TRANSPOSED_SMSS_MIXED_4.txt](https://github.com/OmegaProject/Omega/files/838706/TRANSPOSED_SMSS_MIXED_4.txt)

**Comment by Akramhar** [comment]
should be solved in omega-0.26

**Comment by strambc** [comment]
NOT SOLVED
SAME ISSUE PERSISTS

**Comment by Akramhar** [comment]
should be solved in omega-0.29
