### ISSUE TITLE
OmegaSegmentation: upon saving all selections are reset

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#180]
This is very annoying.
Could something be done about it?

**Comment by Akramhar** [comment]
what "selection" are you talking about?

**Comment by strambc** [comment]
Aren't you on vacation?


Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 13 Mar 2017, at 15:14, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


what "selection" are you talking about?

**Comment by strambc** [comment]
Anyway: the selection of the latest segmentation run

**Comment by Akramhar** [comment]
should be fixed in omega-0.26
