### ISSUE TITLE
OmegaTrajectoryMeasures: CRASHes when performing analysis

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#181]
CRASH 1
12-40
See log

-Using segmented Uniform artificial trajectories
-Using segmented Mixed artificial trajectories

--> Trajectories are segmented.
--> If selecting Default Segmentation run, the default analysis run is present and the graphs are fine.
--> If selecting Saved Segmentation run, and running new Velocity Analysis run, the run does not appear in the selector and graphs do not display.

--> THEN A CRASH OCCURRED (see log)
OMEGA_Testing sessions/2017 OMEGA tests/2017-03-13_OMEGA_2017_PreBetaRelease_v025_test/2017-03-13_12-40_Velocity testing_CRASH

**Comment by strambc** [comment]
[TRANSPOSED_SMSS_MIXED_4.txt](https://github.com/OmegaProject/Omega/files/838935/TRANSPOSED_SMSS_MIXED_4.txt)

[TRANSPOSED_SMSS_0-1_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838932/TRANSPOSED_SMSS_0-1_D_0-0100.txt)
[TRANSPOSED_SMSS_0-3_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838934/TRANSPOSED_SMSS_0-3_D_0-0100.txt)
[TRANSPOSED_SMSS_0-5_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838931/TRANSPOSED_SMSS_0-5_D_0-0100.txt)
[TRANSPOSED_SMSS_0-7_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838930/TRANSPOSED_SMSS_0-7_D_0-0100.txt)
[TRANSPOSED_SMSS_1-0_D_0-0100.txt](https://github.com/OmegaProject/Omega/files/838933/TRANSPOSED_SMSS_1-0_D_0-0100.txt)

**Comment by strambc** [comment]
CRASH 3
13:05
See log

Working only on Uniform artificial trajectory sets.
No segmentation.
Open TMM Browser
Changed colors (random colors)
While selecting trajectories on Browser (control shift select) CRASH OCCURRED (see log)

OMEGA_Testing sessions/2017 OMEGA tests/2017-03-13_OMEGA_2017_PreBetaRelease_v025_test/2017-03-13_13-05_Velocity testing_CRASH_3

**Comment by strambc** [comment]
Appears to be related to #136

**Comment by Akramhar** [comment]
all these problems should be solved with between 0.28 and 0.30
