### ISSUE TITLE
TrajectoryManager: issues with selecting trajectories on Browser

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#182]
This applies to both Editing and Segmentation.

Selecting trajectories is often a problem.
One issue relates with toggling between SHOW (green check mark) vs vs. DON'T SHOW (red cross) buttons.
Sometimes when selecting a trajectory any time on the trajectory length is sensed by the Green/Red toggle listener and then it becomes impossible to select the trajectory.
After a while it appears that the functionality is restored.
Not clear if it is purely time or what...
Does not appear to be purely navigating out or re-selecting.

This is very annoying and I have noticed it multiple times.

**Comment by strambc** [comment]
CLUE (maybe):
when attempting to select a segmented trajectory in the browser the display at the bottom transiently displays: "Graph 100.00 competed"

**Comment by Akramhar** [comment]
should be fixed in omega-0.26
