### ISSUE TITLE
OmegaTrackingMeasures: Diffusivity results table

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#183]
The Track column in the Global Results D and SMSS table does not display the SEGMENT name even when the trajectory has been segmented.

![2017-03-13_mixed 4_segmented_diffusivity results](https://cloud.githubusercontent.com/assets/4050585/23871341/5863e888-0800-11e7-8d1b-214de26825a5.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.26
