### ISSUE TITLE
TrackingMeasures: after diffusivity run trajectory segments order gets scrambled

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#184]
Applies to segmented trajectories.
After running new Analysis run, the order of the segments on the browser gets scrambled.

**Comment by Akramhar** [comment]
Can you give me an example of this?
I tried several times but it doesn't happen to me

**Comment by strambc** [comment]
Could be related to #246

**Comment by Akramhar** [comment]
This should be solved in omega-.34 or omega-0.35
