### ISSUE TITLE
TrackingMeasures: Diffusivity results issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#185]
--I am not sure where slope MSD vs. ∆t log-log plot (global results) is displayed.
I guess it would be great to have it in the "GLOBAL D & SMSS" tab which should then be called "GLOBAL D, slope MSD and SMSS"

--The SMSS and Slope MSD graphs appear to be identical.
Is this normal?

**Comment by strambc** [comment]
![2017-03-13_uniform_d_0-010_0-800_segmented_msd bar graph](https://cloud.githubusercontent.com/assets/4050585/23877191/74d30da2-0817-11e7-8f26-ece8f6e13031.png)
![2017-03-13_uniform_d_0-010_0-800_segmented_mss bar graph](https://cloud.githubusercontent.com/assets/4050585/23877192/74d6e95e-0817-11e7-9909-431e1ce10be8.png)

**Comment by strambc** [comment]
Scales are different but the overall shape seems suspiciously identical...

**Comment by strambc** [comment]
Moved first topic to new issue

**Comment by Akramhar** [comment]
Everything seems fine
