### ISSUE TITLE
TrackingMeasures: slope of MSD vs. ∆t log-log plot (global results) are not available

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#186]
--I am not sure where slope MSD vs. ∆t log-log plot (global results) is displayed.
I guess it would be great to have it in the "GLOBAL D & SMSS" tab which should then be called "GLOBAL D, slope MSD and SMSS"

Related to #185

**Comment by Akramhar** [comment]
should be fixed in omega-0.26
