### ISSUE TITLE
TrackingMeasures: multiple trajectory selection CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#191]
# 2017-03-17_04-22-04
Exception in thread: IntensityGraphProducer
java.lang.reflect.InvocationTargetException : null
java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
edu.umassmed.omega.trackingMeasuresIntensityPlugin.runnable.TMIGraphProducer.updateStatus(TMIGraphProducer.java:166)
edu.umassmed.omega.trackingMeasuresIntensityPlugin.runnable.TMIGraphProducer.run(TMIGraphProducer.java:90)
java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.NullPointerException : null
java.awt.Container.addImpl(Container.java:1093)
java.awt.Container.add(Container.java:417)
edu.umassmed.omega.trackingMeasuresIntensityPlugin.gui.TMIGraphPanel.updateStatus(TMIGraphPanel.java:547)
edu.umassmed.omega.trackingMeasuresIntensityPlugin.runnable.TMIGraphProducer$1.run(TMIGraphProducer.java:169)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

7-03-17_03-10-08	Application started!

# 2017-03-13_01-22-56	Application started!

**Comment by Akramhar** [comment]
should be solved in omega-0.27
