### ISSUE TITLE
TrackingMeasures: launching TMV after TMM _ CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#192]
# 2017-03-17_04-27-03
Exception in thread: MobilityGraphProducer
java.lang.reflect.InvocationTargetException : null
java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.runnable.TMMGraphProducer.updateStatus(TMMGraphProducer.java:181)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.runnable.TMMGraphProducer.run(TMMGraphProducer.java:73)
java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.NullPointerException : null
java.awt.Container.addImpl(Container.java:1093)
java.awt.Container.add(Container.java:973)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.gui.TMMGraphPanel.updateStatus(TMMGraphPanel.java:421)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.runnable.TMMGraphProducer$1.run(TMMGraphProducer.java:184)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Akramhar** [comment]
should be solved in omega-0.27
