### ISSUE TITLE
OmegaTrajectorySegmentation: spot selection mode problem

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#195]
This is the behavior:
Mode Select > Spot

- if no motion type selections have been done yet, work-flow goes at follows: select start spot, select end spot, select motion type, trajectory is painted with assigned color --> WORKS as expected

- after motion type has been selected at least once (for current segmentation job or even from a previous one), work-flow goes as follows: select start spot, select end spot, trajectory is painted with previously selected motion-type color  --> PROBLEM, the flow does not wait for user to select motion type and instead uses the color that had been previously selected

**Comment by Akramhar** [comment]
should be solved in omega-0.29
