### ISSUE TITLE
OmegaTrackingMeasures: color assignment on MSD graph for segmented trajectory

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#197]
Trajectory:
[TRANSPOSED_SMSS_MIXED_4.txt](https://github.com/OmegaProject/Omega/files/859525/TRANSPOSED_SMSS_MIXED_4.txt)

Segmented:
1-100 --> CONFINED
100-166 --> DIRECTED
166-266 --> SUB-DIFFUSIVE
266-267 --> UNASSIGNED
267-367 --> DIFFUSIVE
367-369 --> UNASSIGNED
369-435 --> SUPER-DIFFUSIVE
________________
If all segments are selected including the unassigned segments, the colors of the DIFFUSIVE and SUPER-DIFFUSIVE segments MSD plots in the motion type tab, get scrambled.

if only "assigned" segments are selected the colors are correct.

See screen shots

**Comment by strambc** [comment]
STEP 1: all trajectories are selected:

![image](https://cloud.githubusercontent.com/assets/4050585/24169315/9672138a-0e53-11e7-873b-4f995c1c51e6.png)

**Comment by strambc** [comment]
CASE 2:
only "assigned" trajectories are selected

![image](https://cloud.githubusercontent.com/assets/4050585/24169341/ae74cdd8-0e53-11e7-8085-a002e2265d8c.png)

**Comment by strambc** [comment]
CASE 3: first only "assigned" trajectories are selected, then the two un-assigned segments are added to the selection --> CORRECT COLOR ASSIGNMENTS

![image](https://cloud.githubusercontent.com/assets/4050585/24169415/ed7e086e-0e53-11e7-8529-adc6b79b52aa.png)

**Comment by Akramhar** [comment]
should be solved in omega-0.29
