### ISSUE TITLE
OmegaTrajectoryMeasures: TMM crash --> Graph 22.54 completed

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#198]
BEHAVIOR:

**CASE 1**
When a trajectory is segmented and the analysis is run on all segments, an error appears 
--> Graph 22.54 completed.
Only the first segment is can be graphed.

**CASE 2**
When a trajectory is segmented and the analysis is run on only the first segment (Segment 1-100), the run goes correctly
--> Run ready
Graph for segment 1-100 is shown correctly

**CASE 3**
When a trajectory is segmented and the analysis is run on a single segment (Segment 100-166),  an error appears 
--> Graph 22.54 completed.
No trajectory appears on the browser when the run is selected
No graphs are displayed.

_____________________________
Trajectory:
[TRANSPOSED_SMSS_MIXED_4.txt](https://github.com/OmegaProject/Omega/files/859525/TRANSPOSED_SMSS_MIXED_4.txt)

Segmented:
1-100 --> CONFINED
100-166 --> DIRECTED
166-266 --> SUB-DIFFUSIVE
266-267 --> UNASSIGNED
267-367 --> DIFFUSIVE
367-369 --> UNASSIGNED
369-435 --> SUPER-DIFFUSIVE

**Comment by Akramhar** [comment]
should be solved in omega-0.29
