### ISSUE TITLE
ParticleLinking: the linking CRASHes

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#199]
Linking crashes when more than one image loaded and subjected to PD.
In particular problem is with 
VIRUS snr 7 density high_tSr.tif

**Comment by strambc** [comment]
Tested MOSAIC linking plugin with same image and it worked:
Here is the tracking report
[Traj_VIRUS snr 7 density high_tSr.txt](https://github.com/OmegaProject/Omega/files/863023/Traj_VIRUS.snr.7.density.high_tSr.txt)

**Comment by Akramhar** [comment]
should be fine in omega-0.30
