### ISSUE TITLE
Trajectory name in the interface

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#2]
Rename traj_ to track_
Numeration must be multiple digit (01/001/0001) based on the number of trajectories

**Comment by strambc** [comment]
Sorting has to be numeric including after editing and segmenting trajectories

**Comment by Akramhar** [comment]
The rename should be solved in omega-0.34.
Sorting is related to #246 and it's should be solved in omega-0.34.
The numeration become irrelevant due to the new sorting system.
