### ISSUE TITLE
OmegaTrackingMeasures: TMM CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#200]
Trajectory
[TRANSPOSED_SMSS_MIXED_4.txt](https://github.com/OmegaProject/Omega/files/865900/TRANSPOSED_SMSS_MIXED_4.txt)

Segmented:
1-100 --> CONFINED
100-166 --> DIRECTED
166-266 --> SUB-DIFFUSIVE
266-267 --> UNASSIGNED
267-367 --> DIFFUSIVE
367-369 --> UNASSIGNED
369-435 --> SUPER-DIFFUSIVE

Launch TMM plugin 

CRASH

**Comment by strambc** [comment]
# 2017-03-23_03-14-53
Exception in thread: AWT-EventQueue-0
Ice.ConnectionLostException : null
IceInternal.Outgoing.invoke(Outgoing.java:158)
omero.api._ServiceFactoryDelM.getQueryService(_ServiceFactoryDelM.java:918)
omero.api.ServiceFactoryPrxHelper.getQueryService(ServiceFactoryPrxHelper.java:3261)
omero.api.ServiceFactoryPrxHelper.getQueryService(ServiceFactoryPrxHelper.java:3233)
edu.umassmed.omega.omero.commons.OmeroGateway.loadPlaneInfo(OmeroGateway.java:718)
edu.umassmed.omega.omero.commons.OmeroGateway.computeSizeT(OmeroGateway.java:823)
edu.umassmed.omega.commons.gui.GenericSegmentsBrowserPanel.setImage(GenericSegmentsBrowserPanel.java:648)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.gui.TMMPluginPanel.selectImage(TMMPluginPanel.java:392)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.gui.TMMPluginPanel.access$000(TMMPluginPanel.java:86)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.gui.TMMPluginPanel$2.actionPerformed(TMMPluginPanel.java:319)
javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.gui.TMMPluginPanel.populateImagesCombo(TMMPluginPanel.java:613)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.gui.TMMPluginPanel.<init>(TMMPluginPanel.java:171)
edu.umassmed.omega.trackingMeasuresMobilityPlugin.TMMPlugin.createNewPanel(TMMPlugin.java:86)
edu.umassmed.omega.commons.plugins.OmegaPlugin.getNewPanel(OmegaPlugin.java:73)
edu.umassmed.omega.core.gui.OmegaWorkspacePanel.createNewFrame(OmegaWorkspacePanel.java:381)
edu.umassmed.omega.core.gui.OmegaWorkspacePanel.showNewPanel(OmegaWorkspacePanel.java:297)
edu.umassmed.omega.core.gui.OmegaWorkspacePanel.showPlugin(OmegaWorkspacePanel.java:226)
edu.umassmed.omega.core.gui.OmegaGUIFrame$10.propertyChange(OmegaGUIFrame.java:331)
java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
java.awt.Component.firePropertyChange(Component.java:8428)
java.awt.Component.firePropertyChange(Component.java:8541)
edu.umassmed.omega.core.gui.OmegaPluginLauncherDialog$3.actionPerformed(OmegaPluginLauncherDialog.java:192)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
java.awt.Component.processMouseEvent(Component.java:6533)
javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
java.awt.Component.processEvent(Component.java:6298)
java.awt.Container.processEvent(Container.java:2236)
java.awt.Component.dispatchEventImpl(Component.java:4889)
java.awt.Container.dispatchEventImpl(Container.java:2294)
java.awt.Component.dispatchEvent(Component.java:4711)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
java.awt.Container.dispatchEventImpl(Container.java:2280)
java.awt.Window.dispatchEventImpl(Window.java:2746)
java.awt.Component.dispatchEvent(Component.java:4711)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
java.awt.EventQueue$4.run(EventQueue.java:731)
java.awt.EventQueue$4.run(EventQueue.java:729)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Akramhar** [comment]
I'm unable to reproduce this issue, I need more details.
Did you have omero plugin open? Did you load any image?
What other plugin was open? What other step did you do?

**Comment by strambc** [comment]
MORE DETAILS

Launched app
Open OMERO browser
Loaded 
OMEGA_benchmarking>Chenouard et al. 2014_snr 7_low density>VIRUS snr 7 density low_tSr.tif
(Image ID 58779)

Opened PD but not run

Then loaded the trajectory indicated above etc.

**Comment by Akramhar** [comment]
Did the application stay open for a long time or did you disconnect from OMERO in the meantime?

**Comment by strambc** [comment]
The connection with OMERO was ongoing.
The app was on for not a particularly long time.

Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 23 Mar 2017, at 17:09, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Did the application stay open for a long time or did you disconnect from OMERO in the meantime?

**Comment by Akramhar** [comment]
should be fine in omega-0.30
