### ISSUE TITLE
OmegaSegmentation: transparent CRASH while saving segmentation run

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#201]
Open
Import Trajectory
TRANSPOSED_SMSS_MIXED_4.txt
Segment:
1-100 --> CONFINED
100-166 --> DIRECTED
166-266 --> SUB-DIFFUSIVE
266-267 --> UNASSIGNED
267-367 --> DIFFUSIVE
367-369 --> UNASSIGNED
369-435 --> SUPER-DIFFUSIVE
Save
Segmentation run appears as saved but the display shows unsegmented trajectory.
Nothing on log.

When attempting to save a new segmentation nothing get saved and selection of segmentation run goes to blank

**Comment by strambc** [comment]
More details:
-Same behavior observed when the application was launched again and same workflow was followed.

Noticed the following:
- segmentation run has been saved and is available for Tracking measures
- segmentation run is present and properly recorded on Data Browser
- the TS module Segmentation tab appears to have crashed and not able to refresh any more after save.

**Comment by strambc** [comment]
More details:
the app was launched a third time and the behavior did not reproduce

Differences:
-Same behavior observed when the application was launched again and same workflow was followed.

Noticed the following:
- the first two time (when CRASH occurred) segmentation proceeded from Beginning to end and using SPOT selection mode
-the third time (when CRASH did not occurr) segmentation proceeded from End to Beninning using Motion Type selection mode

**Comment by Akramhar** [comment]
should be solved in omega-0.30
