### ISSUE TITLE
OmegaTrackingMeasures: TMD graph selection area aligned with TMM, TMV and TMI

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#202]
Align the graph selection area of TMD to make it look like the same as for the other TM plugins (TMI, TMM, TMV).

In particular add:

Select Results Type (static label)
Global Results (combobox)

**Comment by strambc** [comment]
![image](https://cloud.githubusercontent.com/assets/4050585/24311165/544854c6-10a9-11e7-9a13-41db615e0980.png)

**Comment by Akramhar** [comment]
should be fine in omega-0.30
