### ISSUE TITLE
OmegaTrackingMeasures: TMM unassigned segments not displayed on global bar graphs

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#204]
TRANSPOSED_SMSS_MIXED_4.txt
Segments
1-100 --> CONFINED
100-166 --> DIRECTED
166-266 --> SUB-DIFFUSIVE
266-267 --> UNASSIGNED
267-367 --> DIFFUSIVE
367-369 --> UNASSIGNED
369-435 --> SUPER-DIFFUSIVE

IN TMM:
When some of the global measures are selected: e.g. Total Distance Traveled, Confinement Ratio, Total Net Displacement only ASSIGNED trajectories are displayed on graph.

When other measures are selected: e..g. Total Time Traveled, all segments are displayed.

NOTE: in TMV all measures show all segments including non assigned.

**Comment by Akramhar** [comment]
seems to be resolved in omega-0.31
