### ISSUE TITLE
OmegaTrajectory Manager: TE CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#205]
2017-03-28_ CRASH

Launch
Open IB
Open Chenouard et al. 2014 snr 7_low density
>VIRUS snr 7 density low

PD with default parameter, 
PL with filter out trajectories smaller than 50/Movement type: straight line

Open Trajectory Manager
TE
Try to resize window

NON RESPONSIVE

see PD and core logs below

**Comment by strambc** [comment]
PD log
# 2017-03-28_06-35-52	Application started!

# 2017-03-28_06-28-43	Pulling results from SDWorkers

# 2017-03-28_06-28-38	Creating 100 SDWorkers for VIRUS snr 7 density low_tSr.tif

# 2017-03-28_06-26-42	Application started!

# 2017-03-27_12-51-25	Application started!

# 2017-03-27_12-46-34	Pulling results from SDWorkers

# 2017-03-27_12-46-29	Creating 100 SDWorkers for VIRUS snr 7 density low_tSr.tif

# 2017-03-27_12-46-17	Pulling results from SDWorkers

# 2017-03-27_12-46-16	Creating preview 0 SDWorker for VIRUS snr 7 density low_tSr.tif

# 2017-03-27_12-20-32	Application started!

# 2017-03-27_11-41-42	Pulling results from SDWorkers

# 2017-03-27_11-41-38	Creating 100 SDWorkers for VIRUS snr 7 density low_tSr.tif

# 2017-03-27_11-41-18	Pulling results from SDWorkers

# 2017-03-27_11-41-11	Creating 100 SDWorkers for VIRUS snr 7 density low_tSr.tif

# 2017-03-27_11-38-33	Application started!

# 2017-03-27_10-50-56	Application started!

**Comment by strambc** [comment]
Core log

# 2017-03-28_06-35-52	VM options: 

# 2017-03-28_06-35-52	Application started!

# 2017-03-28_06-26-39	VM options: 

# 2017-03-28_06-26-39	Application started!

# 2017-03-27_12-51-25	VM options: 

# 2017-03-27_12-51-25	Application started!

# 2017-03-27_12-20-32	VM options: 

# 2017-03-27_12-20-32	Application started!

# 2017-03-27_11-38-33	VM options: 

# 2017-03-27_11-38-33	Application started!

# 2017-03-27_10-50-52	VM options: 

# 2017-03-27_10-50-52	Application started!

**Comment by Akramhar** [comment]
should be fixed in omega-0.31
