### ISSUE TITLE
OMEGATrackingMeasures: Diffusivity --> Minimum detectable D

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#211]
The following has to be done:

- [x] - expose the minimum detectable D values to the phase space graph
- [x] - save the result to diffusivity results (field name MiniDetectableODC)
- [ ] - implement the database aspect of it

**Comment by Akramhar** [comment]
should be solved in omega-0.30

**Comment by strambc** [comment]
The MiniDetectableODC is not exposed in diffusivity results.
I am not sure whether the database aspect of it has been solved.

**Comment by Akramhar** [comment]
should be solved in omega-0.35
