### ISSUE TITLE
SNREstimation: various issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#213]
Sbalzarini (TBD) should be renamed >>> Cheezum

SNR Method should be renamed >>>> SNR Model

ROI results: missing SNR and Noise

Check what is displayed in the Bkg column.

SNR Estimation: General quadrant of Run Definition contains PD results and it is not consistent with the behavior of the linking algorithm. The two behaviors should be aligned.

**Comment by Akramhar** [comment]
should be solved in omega-0.31
the bkg column contains the image bkg
