### ISSUE TITLE
General Results panel: refreshing results behavior

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#215]
1) Particle detector case: multiple runs have been executed on the same image

when the folder icon is selected the General results panel shows: "No Details Available" while the results table still displays the last selected results dataset.

-->>>The behavior should be that when the folder is selected no results are displayed in either the general panel or the results table.

2) SNR Estimation case: multiple runs have been executed on the same particle detection run

when toggling through different selections such as a folder or a particle detection with no SNR results yet, the results do not refresh at all (neither the general or the table).

-->>>The behavior should be that when an item with no directly attached results is selected no results are displayed in either the general panel or the results table.

**Comment by Akramhar** [comment]
should be fixed in omega-0.31

**Comment by strambc** [comment]
1. POINT 1 is solved
2. POINT 2 could not be tested because of CRASH #253
