### ISSUE TITLE
SNR Estimation: CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#217]
BEHAVIOR
loaded VIRUS snr 7 density low_tSr.tif
run PD
attempt to run SNR Estimaton
CRASH

Log core
# 2017-04-10_06-22-21
Exception in core
Exception in thread: Thread-469
java.lang.NullPointerException : null
edu.umassmed.omega.snrSbalzariniPlugin.runnable.SNREstimator.run(SNREstimator.java:125)
java.lang.Thread.run(Thread.java:745)

**Comment by Akramhar** [comment]
Need more information, impossible to reproduce the issue atm

**Comment by strambc** [comment]
Related with #253 ?
