### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#220]
Application left idle for a bit over an hour.
When attempting to execute a linking run CRASH:

# 2017-04-11_03-11-44
Exception in core
Exception in thread: AWT-EventQueue-0
Ice.ConnectionLostException : null
IceInternal.Outgoing.invoke(Outgoing.java:158)
omero.api._RenderingEngineDelM.setCompressionLevel(_RenderingEngineDelM.java:2248)
omero.api.RenderingEnginePrxHelper.setCompressionLevel(RenderingEnginePrxHelper.java:8217)
omero.api.RenderingEnginePrxHelper.setCompressionLevel(RenderingEnginePrxHelper.java:8189)
edu.umassmed.omega.omero.commons.OmeroGateway.setCompressionLevel(OmeroGateway.java:912)
edu.umassmed.omega.core.gui.OmegaElementRenderingPanel.addRenderingControl(OmegaElementRenderingPanel.java:373)
edu.umassmed.omega.core.gui.OmegaElementRenderingPanel.setRenderingControl(OmegaElementRenderingPanel.java:509)
edu.umassmed.omega.core.gui.OmegaSidePanel.updateCurrentElement(OmegaSidePanel.java:485)
edu.umassmed.omega.core.gui.OmegaSidePanel.updateCurrentElement(OmegaSidePanel.java:431)
edu.umassmed.omega.core.gui.OmegaSidePanel.manageItemChanged(OmegaSidePanel.java:380)
edu.umassmed.omega.core.gui.OmegaSidePanel.updateGUI(OmegaSidePanel.java:513)
edu.umassmed.omega.core.gui.OmegaGUIFrame.updateGUI(OmegaGUIFrame.java:554)
edu.umassmed.omega.core.OmegaApplication.updateGUI(OmegaApplication.java:1421)
edu.umassmed.omega.core.OmegaApplication.handlePluginEventAlgorithm(OmegaApplication.java:803)
edu.umassmed.omega.core.OmegaApplication.handlePluginEvent(OmegaApplication.java:710)
edu.umassmed.omega.commons.plugins.OmegaPlugin.fireEvent(OmegaPlugin.java:134)
edu.umassmed.omega.plSbalzariniPlugin.gui.PLPluginPanel.updateRunnerEnded(PLPluginPanel.java:491)
edu.umassmed.omega.plSbalzariniPlugin.gui.PLPluginPanel.updatePLRunnerMessageStatus(PLPluginPanel.java:747)
edu.umassmed.omega.plSbalzariniPlugin.gui.PLPluginPanel.updateMessageStatus(PLPluginPanel.java:754)
edu.umassmed.omega.plSbalzariniPlugin.runnable.PLRunner$2.run(PLRunner.java:406)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Akramhar** [comment]
The fact that there is a crash is normal because after 1 hour of inactivity the connection with OMERO is lost. The way the crash is handled should be fixed in omega-0.31.
