### ISSUE TITLE
Tracking Measures: trajectory selection

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#221]
When in Tracking Measures, trajectory selection works well when it is done on the Browser.

Applies to all TM types.

The other way around, when selection is done on the image it does not work well and when selection is achieved all trajectories get selected all at once.

**Comment by Akramhar** [comment]
Should be fixed in omega-0.33.

**Comment by strambc** [comment]
Mostly fixed but see #228 for some remaining issues
