### ISSUE TITLE
ParticleLinking: selecting additional particle detection run

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#226]
Image:
 I1_CMMT_7hPT_GagGFP_Cherrytub_untreated_01_R3D_D3D.dv

Run multiple detector runs and multiple linking runs.

Selector of loaded data is able to properly select pd/pl runs to display on side bar when any of the PL runs of the the first PD run are selected.
When moving to another PD run, the selector is able to properly select the PD run alone (displaying detected particles on the side bar image) but not associated PL runs. 
When an associated PL run is selected the first PD/PL couple is displayed.

**Comment by strambc** [comment]
OBSERVATIONS:
1) same exact behavior is observed when selection is done on Data Browser
2) if all PL runs are deselected from the first PD run no trajectories are showed on the side bar when the second PD run is selected.
3) if all PL runs but one are deselected from the first PD run only the remaining trajectories are showed on the side bar when the second PD run is selected.

**Comment by strambc** [comment]
OBSERVATIONS 2:

1. when selection is done on the trajectory browser panel the image seem to adjourn but the selector on the side panel does not update.
2. the colors chosen on the TB are shown also on the side bar
3. the zoom in works.

OBSERVATION 3:
1. Selection of trajectories on the SIDE BAR is not working even when mouse is pointing to one of the bends.

**Comment by Akramhar** [comment]
should be fixed omega-0.33

**Comment by strambc** [comment]
Additional issues remaining see: #233
