### ISSUE TITLE
SideBar: faulty selection of trajectory on image and faulty synch with TB

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#228]
Trajectory selection on image in side bar has stopped working.
Case>>
Image: I1_CMMT_7hPT_GagGFP_Cherrytub_untreated_01_hstk_CROP2.tif
DS: OMEGA benchmarking>OMEGA real life etc.

PD and PL parameters
Radius 3
Cutoff 3
Percentile 0.5

Straight line
D 10
LR 2
Filter >25

**Comment by strambc** [comment]
OBSERVATION: 
Case>>
Image: VIRUS snr7 low_tSr.tif
DS: OMEGA benchmarking>Chenouard et al 2014_snr7_low density
PD and PL parameters
Radius 3
Cutoff 3
Percentile 0.1
Straight line
D 10
LR 2
Filter >25

Contrary to what described for the dual color image above, in this case (single color artificial image)
PD/PL results in MOSAIC vs. OMEGA are almost completely overlapping with a few exceptions related to the LINK RANGE parameter (described here #230)

**Comment by strambc** [comment]
FURTHER OBSERVATION: in the case of the single color VIRUS snr7 low image selection on the side-bar image appeared to work fine except the selection did not sink with TB and also the selection was not working on the TB side (TB in both TManager and TMeasures). 
When the application was relaunched, the selection from TB resumed working and sinking with that on the side-bar image however now the selection initiated from the side-bar image did not work any more.

THE BEHAVIOR LOOKS LIKE THE TWO SELECTION ARE MUTUALLY EXCLUSINVE.
Case>>
Image: VIRUS snr7 low_tSr.tif
DS: OMEGA benchmarking>Chenouard et al 2014_snr7_low density
PD and PL parameters
Radius 3
Cutoff 3
Percentile 0.1
Straight line
D 10
LR 2
Filter >25

**Comment by strambc** [comment]
Same behavior observed with  C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2.tif (single color image).
Selection from SideBar appears to cause a crash >> TB browser behaves very erratically. See attached Screen Shot

**Comment by strambc** [comment]
![sidebar trajectory selection crash](https://cloud.githubusercontent.com/assets/4050585/25295665/7afd0d90-26b2-11e7-9144-9b929019be7e.png)

**Comment by Akramhar** [comment]
should be solved in omega-0.34

**Comment by strambc** [comment]
OBSERVATION: CRASH behavior confirmed.
SELECTION on SideBar caused a CRASH.
Nothing on log.

![sidebar trajectory selection crash_ii](https://cloud.githubusercontent.com/assets/4050585/25359737/44da3292-2914-11e7-9595-9cdc7666cb93.png)

**Comment by strambc** [comment]
Hi
Just checking.
Did you also solve the CRASH behavior?


Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 24 Apr 2017, at 17:24, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #228<https://github.com/OmegaProject/Omega/issues/228> to @strambc<https://github.com/strambc>.

**Comment by Akramhar** [comment]
There was a crash happening behind the scene when selecting tracks on the sidebar image.
It seems that removing that issue solved everything.

**Comment by strambc** [comment]
On TMeas TB selection works fine in both directions.
Expected behavior is met.
On TE and TS TB selection works fine from SideBar but not from TB side. 
Opened a new issue --> #258
