### ISSUE TITLE
PD/PL: MOSAIC vs OMEGA behavior discrepancy II

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#230]
Contrary to what observed with #231, in this case, PD/PL results in MOSAIC vs. OMEGA are almost completely overlapping with a few exceptions related to the LINK RANGE parameter: total number of trajectories is 64 in MOSAIC and 61 in OMEGA.
The trajectories that appear to be missing from OMEGA all have a ARTIFICIALLY ADDED connecting link put in by the algorithm. The trajectory completely absent in OMEGA.

Hypothesis: discrepancy is due to the effect of the LINKING RANGE parameter.

Case>>
Image: VIRUS snr7 low_tSr.tif
DS: OMEGA benchmarking>Chenouard et al 2014_snr7_low density
PD and PL parameters
Radius 3
Cutoff 3
Percentile 0.1
Straight line
D 10
LR 2
Filter >25

**Comment by strambc** [comment]
Alex suggested it might instead be due to the FILTER parameter.
Spent some times comparing results with FILTER set to Min Trajectory Length = 0.
The results appear to be more aligned between MOSAIC and OMERO but there are still some discrepancies (see attached results).

**Comment by strambc** [comment]
![c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_particles snapshot](https://cloud.githubusercontent.com/assets/4050585/25359953/3dbd1b54-2915-11e7-8643-c415cab46890.png)
![c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_sl-2-15_f30 trajectories snapshot](https://cloud.githubusercontent.com/assets/4050585/25359952/3dbcee2c-2915-11e7-9d4b-754c13768e70.png)
[C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2_3-3-01_SL-2-15_results.txt](https://github.com/OmegaProject/Omega/files/953251/C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2_3-3-01_SL-2-15_results.txt)
![c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_sl-2-15_summary](https://cloud.githubusercontent.com/assets/4050585/25359951/3dba4be0-2915-11e7-9d2d-d73f0cedd955.png)

**Comment by strambc** [comment]
![o_c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_particles snapshot](https://cloud.githubusercontent.com/assets/4050585/25360037/8229fdfc-2915-11e7-85f5-c140bf10c992.png)
![o_c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_sl-2-15_f30 trajectories snapshot](https://cloud.githubusercontent.com/assets/4050585/25360040/823114ca-2915-11e7-83fd-944ac3dc3128.png)
[O_C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2_3-3-01_SL-2-15_PD_results.txt](https://github.com/OmegaProject/Omega/files/953255/O_C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2_3-3-01_SL-2-15_PD_results.txt)
![o_c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_sl-2-15_pd_summary](https://cloud.githubusercontent.com/assets/4050585/25360039/822c0c6e-2915-11e7-9d09-1004eab59a07.png)
[O_C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2_3-3-01_SL-2-15_PL_results.txt](https://github.com/OmegaProject/Omega/files/953256/O_C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2_3-3-01_SL-2-15_PL_results.txt)
![o_c1-i1_cmmt_7hpt_gaggfp_untreated_01_hstk_crop2_3-3-01_sl-2-15_pl_summary](https://cloud.githubusercontent.com/assets/4050585/25360038/822ac70a-2915-11e7-9c4c-f8d11d718c76.png)

**Comment by Akramhar** [comment]
should be solved in omega-0.35

**Comment by strambc** [comment]
Conducted extensive tests.
Particle detection was identical within the 7th decimal digit
Trajectories were the same nr.
Positions within trajectories were very similar to the 3rd decimal digit.
