### ISSUE TITLE
PD/PL: MOSAIC vs OMEGA behavior discrepancy I

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#231]
This issue replaces issue #229 

When comparing results obtained with PD/PL MOSAIC vs. OMEGA several discrepancies were observed. Most trajectories were totally different.
In addition, spots appear off with respect from actual observed bright-spots, spots are not identified in a weird one-on/one-off pattern and trajectories cannot be selected on image (for the latter see also  #228). This is apparent both on the side-bar and on the TB.

Case>>
Image: I1_CMMT_7hPT_GagGFP_Cherrytub_untreated_01_hstk_CROP2.tif
DS: OMEGA benchmarking>OMEGA real life etc.

PD and PL parameters
Radius 3
Cutoff 3
Percentile 0.5

Straight line
D 10
LR 2
Filter >25

**Comment by strambc** [comment]
After observing the behavior reported in #230 the strong hypothesis emerged that the discrepancies described here are due to the fact that the image in OMEGA is a dual color image (while the ImageJ MOSAIC plugin can only work with split-channel images).
This hypothesis was confirmed by @Akramhar who discovered that because of the ImageJ implementation we are now using in OMEGA channels are not split properly during execution of PD.

**Comment by Akramhar** [comment]
the problem with channels has been resolved in omega-0.34

**Comment by strambc** [comment]
Great

Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 24 Apr 2017, at 17:33, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


the problem with channels has been resolved in omega-0.34

**Comment by strambc** [comment]
Tested by repeating case 1 as above.
NOTE --> note that the parameters for particle detection had to be adjusted. Not clear why.
__________
Algorithm: MOSAIC feature point detection
--
Parameters:
Radius: | 3
Cutoff: | 0.001
Percentile: | 0.1
Absolute Percentile | FALSE
Analyzed Z-plane | 0
Analyzed Channel | 0
Executed:   2018-10-10 02-14-34
Times Analyzed | 2
Average number of spots found per time   poin | 12.887
Max    number of spots found per time point | 17
Min    number of spots found per time point | 8


[2018-10-10_Issue #231_tests.xlsx](https://github.com/OmegaProject/Omega/files/2466051/2018-10-10_Issue.231_tests.xlsx)
