### ISSUE TITLE
PD/PL: faulty selection of PD and PL runs when additional PD runs are present

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#233]
Connected and replacing #226
Still problems with selection of PD and PL.
Case >>
two images Image 1 "VESICLE snr 7 density low" and  Image 2 "VIRUS snr 7 density low"
Both have undergone 1 PD and 1 PL runs.
See below for PD/PL parameters

# 1) FIRST PHASE only PD run has been executed:

### PD plugin:
Selecting Image 1 run works: display results, display correct image and correct PD run on sidebar
Selecting Image 2 run does not work: displays results, displays correct image but does not refresh to correct PD run sidebar (including Tracks selector).

### Data Browser:
same behavior as PD plugin. 
Image 2 run does not appear at all on Particle Detection area.
When Image 2 is deselected and selected again (check box) then the run appears but still does not refresh the side bar view accordingly.
Another weird behavior: when selecting Image1 on DB, the sidebar view refreshes correctly and the PD plugin view refreshed and the correct PD run is highlighted and results display correctly.
When selecting Image2 on DB, the sidebar view refreshes only the image but not the PD run and on the PD plugin the highlighting is limited to the Image level and does not extend to the PD run level (see images below). Also results do not display.

### Data Browser
**Issue with un-checking backwards up the data tree**(see #236)
When un-checking and re-checking the PD run  the PD detection does not refresh on the side-bar and the results do not refresh on the PD plugin (results remain displayed and PD run disappears from the image tree). 
In order to get the whole thing to work again one has to un-check the image and start over down the tree. However the following is observed: when checking the Image, the PD plugin displays Image and PD run (folder open). When checking the PD run the image folder collapses and the PD run disappears from the Loaded Data area of the PD plugin.

FINAL OBSERVATION:
if both Image1 and 2 are UN-checked on Data Browser and one goes down the tree for Image2 now the selection of data on both Side Bar and PD plugin work ok with results, image, PD detection and Tracks selector refreshing properly (except the Image "folder" on the Loaded Data area of the PD plugin remains collapsed).

_______________________
PD and PL parameters
Radius 3
Cutoff 3
Percentile 0.1
Straight line
D 10
LR 2
Filter >25

**Comment by strambc** [comment]
# 2) SECOND PHASE both PD and PL runs have  been executed:
## a) Both images are checked on the DB

Data Browser:
One of the two images de-selected (un-checked) / Selection forward (clicking down the chain)
Selection from DB appears to work fine.

**Comment by strambc** [comment]
# 3) THIRD PHASE both PD and PL runs have  been executed:
## a) Both images are checked on the DB

Data Browser:
One of the two images de-selected (un-checked) / Selection forward (clicking down the chain)
Selection from DB appears to work fine.

**Comment by strambc** [comment]
![image 1 selection on db](https://cloud.githubusercontent.com/assets/4050585/25294369/d2a2ec5a-26ac-11e7-86fc-176254848734.png)
![image 2 selection on db](https://cloud.githubusercontent.com/assets/4050585/25294368/d2a0635e-26ac-11e7-801f-251316242489.png)

**Comment by Akramhar** [comment]
should be solved in omega-0.34

**Comment by strambc** [comment]
OBSERVATIONS:
some issues have been solved but in general behavior of selection/deselection is still not as desired.
Should go over it together to define desired behavior.
New issue opened for that purpose --> #261
In the mean time:

## PHASE 3
Selection of different images is working fine. Selection of PD vs PL runs is not quite working because TRAJECTORIES ARE ALWAYS SHOWN regardless of whether one selects PD runs or PL runs. So when different PD runs are selected the image changes (as appropriate) however the trajectories are always shown. While when selecting a PD run only particles should be shown even when a PL run has been executed on that same image/PD run. Refer to #261 for desired behavior

**Comment by strambc** [comment]
## Phase 1
Selection from PD works.
Selection from DB still faulty (see #261 for desired behavior).

**Comment by strambc** [comment]
## PHASE 2
Selection on PD and PL works.
Selection from DB works at the image level. Lower levels still faulty (see #261 for desired behavior).

**Comment by Akramhar** [comment]
should be fixed in omega-0.35.
if something is not fixed this issue should be closed anyway and a new issue should be opened.

**Comment by strambc** [comment]
When testing PARAMETERS had to be changed due to the fact that the MOSAIC version used in v035 has changed with respect to v033.

PD:
-Radius: 2
-Cutoff: 0.2
-Percentile: 0.1
PL
-Displacement: 20.0
-Link Range: 1
-Movement Type: Brownian
-Object Feature: 1.0
-Dynamics: 1.0
-Optimizer: Greedy
-Min Track Length: 25

**Comment by strambc** [comment]
1a --> Closed
1b -->  Opened new issue #292

**Comment by strambc** [comment]
3a --> Opened new issue #294
PD plugin: when selecting PD run the SideBar displays trajectories as well.
Specifically, TRAJECTORIES ARE ALWAYS SHOWN regardless of whether one selects PD runs or PL runs. So when different PD runs are selected the image changes (as appropriate) however the trajectories are always shown. While when selecting a PD run only particles should be shown even when a PL run has been executed on that same image/PD run.
