### ISSUE TITLE
CRASH: Exception in thread: SDRunner2

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#234]
# 2017-04-20_06-31-59
Exception in thread: SDRunner2
java.lang.NullPointerException : null
edu.umassmed.omega.sdSbalzariniPlugin.runnable.SDRunner2.normalModeRun(SDRunner2.java:209)
edu.umassmed.omega.sdSbalzariniPlugin.runnable.SDRunner2.run(SDRunner2.java:130)
java.lang.Thread.run(Thread.java:745)

**Comment by Akramhar** [comment]
I need more information here.
How can I reproduce the problem?

**Comment by Akramhar** [comment]
There is a chance this could be solved in omega-0.34
