### ISSUE TITLE
PD: two runs executed at the same time have identical name

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#235]
Two images,  "VIRUS snr 7 density low" and "VESICLE snr 7 density low"
Loaded on PD execution queue one after the other and then executed at the same time.
Have identical names.
Could be a problem?

**Comment by Akramhar** [comment]
shouldn't be a problem if they are from different images.
need to be investigated if you can obtain same name in one image.

**Comment by Akramhar** [comment]
should be automatically solved by modification done for #252
