### ISSUE TITLE
SNR Estimation: run is not available in Select SNR estimation

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#237]
SNR Estimation was the SNR run but was not available in TM Diffusivity Run tab.
See attached screen shot

____________________
Three image open
OMEGA_benchmarking>> VIRUS snr 7 density low_ISOLATED TRAJECTORIES>> 
VIRUS snr 7 density low_Trajectory 113.tif
VIRUS snr 7 density low_Trajectory 33.tif
VIRUS snr 7 density low_Trajectory 61.tif

Only one image analyzed >> VIRUS snr 7 density low_Trajectory 113.tif
PD/PL parameters
Results with OMEGA
Radius 3, Cutoff radius 3.0, Percentile 0.1
Displacement 10.0, Linkrange 2, Straight lines, OF 1, D 1, Optimizer Greedy
Min Track Length 0
Found 47 trajectories

SNR Parameters
Radius: 3, Threshold: 0.8, SNR Model: Cheezum

![screen shot 2017-04-25 at 15 40 53](https://cloud.githubusercontent.com/assets/4050585/25404400/cbc7a88e-29cd-11e7-8780-4cdc672b34a7.png)

**Comment by strambc** [comment]
OBSERVATION:
when the SNR run was selected on the Data Browser then it became available in the TM Diffusivity Run tab.


![screen shot 2017-04-25 at 15 53 27](https://cloud.githubusercontent.com/assets/4050585/25404846/6001c98e-29cf-11e7-9a5d-bd8bc3443899.png)

**Comment by Akramhar** [comment]
should be solved in omega-0.34

**Comment by strambc** [comment]
OBSERVATION:
now the  SNR run is indeed available on TM-Diffusivity Run tab.
However upon first selection of the tab the display behavior is still faulty:
Even if Error disabled is the default selection, the correct available SNR estimation run shows up in the selector despite the fact that it should not.

DESIRED BEHAVIOR:

upon first selection --> Error disabled selected by default, Select SNR estimation --> should be blank 
upon selection of Error option --> Error enabled the available SNR Estimation run should appear

NOTE upon selection of Error option --> Error disabled after Error enabled has been selected once the correct behavior is displayed (see screenshot).
![screen shot 2017-05-05 at 13 35 15](https://cloud.githubusercontent.com/assets/4050585/25757229/b4295e12-3197-11e7-82d0-4952f796ec3a.png)

**Comment by strambc** [comment]
Closed and moved remaining issues to #275
