### ISSUE TITLE
Error Analyis: works with 1 but does not work with multiple trajectories

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#238]
Case identical to that reported in #237.
Attempted to run analysis with Error Enabled 
It worked with 1 single trajectory but not with more than 1.
When all trajectories were run, the algorithm appeared to get stuck on Trajectory_5 6/27

**Comment by strambc** [comment]
Attempted to do it again with 1 single image loaded:
Only one image analyzed >> VIRUS snr 7 density low_Trajectory 113.tif

Worked with 1 trajectory (Traj_4_Segm_10-46)
Worked with 4 trajectories (Traj_4_Segm_10-46, Traj_3_Segm_10-30, Traj_2_Segm_7-30, Traj_1_Segm_7-13)

DID NOT WORK with ALL TRAJECTORIES

**Comment by Akramhar** [comment]
this should be solved in omega-0.34
