### ISSUE TITLE
General Top-Data selector containing plugin windows: Menus disappear when window undocked

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#239]
Same issue as #109
BEHAVIOR might be Mac specific and it is definitely dependent on the presence of loaded data

When data is loaded and TMeas Diffusivity is undocked menus disappear from the top of the window.
This does happens with all similar top-data-selector containing plugin windows when data is loaded.

![screen shot 2017-04-25 at 16 42 06](https://cloud.githubusercontent.com/assets/4050585/25407422/427a9c7a-29d8-11e7-919e-fa9d0eeb9452.png)

_______________
CASE DESCRIPTION
Only one image open and analyzed >> OMEGA_benchmarking>> VIRUS snr 7 density low_ISOLATED TRAJECTORIES>>VIRUS snr 7 density low_Trajectory 113.tif

PD/PL parameters
Results with OMEGA
Radius 3, Cutoff radius 3.0, Percentile 0.1
Displacement 10.0, Linkrange 2, Straight lines, OF 1, D 1, Optimizer Greedy
Min Track Length 0
Found 47 trajectories

SNR Parameters
Radius: 3, Threshold: 0.8, SNR Model: Cheezum

**Comment by strambc** [comment]
When no data is loaded the same plugin windows behave normally when docked and when un-docked.

![screen shot 2017-04-25 at 16 54 46](https://cloud.githubusercontent.com/assets/4050585/25407635/11787c5e-29d9-11e7-8ff0-b78162ff8ba9.png)

**Comment by strambc** [comment]
OBSERVATION:
when attempting to reproduce the behavior one more time with loaded data could not be reproduced.
However this same behavior had been observed previously.
Will make a note when it happens again.

**Comment by strambc** [comment]
Same issue as #109

**Comment by Akramhar** [comment]
closed because duplicate

**Comment by strambc** [comment]
Closed #109 (which is older instead of this)

**Comment by strambc** [comment]
We need a better analysis of this problem to be able to replicate it as needed

**Comment by strambc** [comment]
Here is the problem again:

TS when docked it is all fine.
When undocked menu items disappear.

![screen shot 2017-04-28 at 15 10 59](https://cloud.githubusercontent.com/assets/4050585/25543657/72818b64-2c25-11e7-928f-5ce87eb97f6f.png)

**Comment by strambc** [comment]
Then when the plugin is docked again here are the menus again:
![screen shot 2017-04-28 at 15 17 46](https://cloud.githubusercontent.com/assets/4050585/25543775/de1af9a0-2c25-11e7-9111-90c9f3189f97.png)

**Comment by strambc** [comment]
Same issue represented itself repeatedly during the same testing session even across applications re-launches

**Comment by Akramhar** [comment]
![image](https://cloud.githubusercontent.com/assets/3996749/25596083/68f99358-2e95-11e7-8cf3-f75abc4948b9.png)
Behaviour didn't show up AT ALL in any of my Windows Test

**Comment by Akramhar** [comment]
Did you check if the Menu is showing in the MAC top bar?

**Comment by strambc** [comment]
What is the Mac top bar?

On May 1, 2017, at 17:43, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you check if the Menu is showing in the MAC top bar?

**Comment by strambc** [comment]
It is probably MAC specific.
But it is real.

On May 1, 2017, at 21:52, Caterina Strambio De Castillia <caterina.strambio@umassmed.edu<mailto:caterina.strambio@umassmed.edu>> wrote:

What is the Mac top bar?

On May 1, 2017, at 17:43, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you check if the Menu is showing in the MAC top bar?

**Comment by Akramhar** [comment]
[Mac Menu Bar](https://www.google.com/imgres?imgurl=http://desktopspotting.com/wp-content/uploads/2011/12/dark-Menu-Bar-Mac-OS-X.jpg&imgrefurl=http://desktopspotting.com/tag/mac-menu-bar/&h=312&w=458&tbnid=Y4LYNLb8MGw8JM:&tbnh=160&tbnw=235&usg=__sBJCWRY3OPVOjnu1xYmQrbzKz_A=&vet=10ahUKEwjrq9mLjtDTAhWLzIMKHc5yBZAQ9QEIKzAA..i&docid=OIJg4EYBkRmOeM&sa=X&ved=0ahUKEwjrq9mLjtDTAhWLzIMKHc5yBZAQ9QEIKzAA)

**Comment by strambc** [comment]
why would it be there?

On May 1, 2017, at 21:59, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Mac Menu Bar<https://www.google.com/imgres?imgurl=http://desktopspotting.com/wp-content/uploads/2011/12/dark-Menu-Bar-Mac-OS-X.jpg&imgrefurl=http://desktopspotting.com/tag/mac-menu-bar/&h=312&w=458&tbnid=Y4LYNLb8MGw8JM:&tbnh=160&tbnw=235&usg=__sBJCWRY3OPVOjnu1xYmQrbzKz_A=&vet=10ahUKEwjrq9mLjtDTAhWLzIMKHc5yBZAQ9QEIKzAA..i&docid=OIJg4EYBkRmOeM&sa=X&ved=0ahUKEwjrq9mLjtDTAhWLzIMKHc5yBZAQ9QEIKzAA>

**Comment by strambc** [comment]
Anyway, you are right it is in the Mac Menu Bar.
Why is it there?
I
On May 1, 2017, at 22:00, Strambio, Caterina <Caterina.Strambio@umassmed.edu<mailto:Caterina.Strambio@umassmed.edu>> wrote:

why would it be there?

On May 1, 2017, at 21:59, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Mac Menu Bar<https://www.google.com/imgres?imgurl=http://desktopspotting.com/wp-content/uploads/2011/12/dark-Menu-Bar-Mac-OS-X.jpg&imgrefurl=http://desktopspotting.com/tag/mac-menu-bar/&h=312&w=458&tbnid=Y4LYNLb8MGw8JM:&tbnh=160&tbnw=235&usg=__sBJCWRY3OPVOjnu1xYmQrbzKz_A=&vet=10ahUKEwjrq9mLjtDTAhWLzIMKHc5yBZAQ9QEIKzAA..i&docid=OIJg4EYBkRmOeM&sa=X&ved=0ahUKEwjrq9mLjtDTAhWLzIMKHc5yBZAQ9QEIKzAA>

**Comment by Akramhar** [comment]
Because that's how MAC handles menu from floating windows.
It does that with every application.
