### ISSUE TITLE
TMeas Diffusivity: faulty display of trajectories selected in TB 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#240]
Executed Diffusivity run with Error Enabled on 4/47 trajectories.
When the run is selected all trajectories are shown in the Trajectory plot of the motion type tab.
Conversely, only the available trajectories are present in the other graphs.

When trajectories are selected in the Browser tab only those are displayed in all four motion type panels.

![screen shot 2017-04-25 at 17 33 04](https://cloud.githubusercontent.com/assets/4050585/25408835/73995a08-29dd-11e7-931c-af52c6eaf6de.png)
![screen shot 2017-04-25 at 17 33 17](https://cloud.githubusercontent.com/assets/4050585/25408834/7397a320-29dd-11e7-97d1-7cd4e810f10c.png)
![screen shot 2017-04-25 at 17 33 35](https://cloud.githubusercontent.com/assets/4050585/25408836/739a5cc8-29dd-11e7-83e6-12038d9ef375.png)
![screen shot 2017-04-25 at 17 33 45](https://cloud.githubusercontent.com/assets/4050585/25408837/739d6be8-29dd-11e7-8b52-6e05ce7643e1.png)

_______________
CASE DESCRIPTION
Only one image open and analyzed >> OMEGA_benchmarking>> VIRUS snr 7 density low_ISOLATED TRAJECTORIES>>VIRUS snr 7 density low_Trajectory 113.tif

PD/PL parameters
Results with OMEGA
Radius 3, Cutoff radius 3.0, Percentile 0.1
Displacement 10.0, Linkrange 2, Straight lines, OF 1, D 1, Optimizer Greedy
Min Track Length 0
Found 47 trajectories

A second PL run present with same parameters but Min Track Length 25

SNR Parameters
Radius: 3, Threshold: 0.8, SNR Model: Cheezum

**Comment by Akramhar** [comment]
should be solved in omega-0.34
