### ISSUE TITLE
TMeas Diffusivity: different symbols used on the scatter plot vs. other three graphs

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#243]
Symbols used to display a trajectory on the Phase Space graph are different with respect to the other three graphs making things very confusing.

![screen shot 2017-04-25 at 17 57 33](https://cloud.githubusercontent.com/assets/4050585/25409649/cee59036-29e0-11e7-9621-2d15ef7cf7ee.png)

![screen shot 2017-04-25 at 17 58 44](https://cloud.githubusercontent.com/assets/4050585/25409660/daad98a0-29e0-11e7-9c65-28ceaf2e1490.png)
![screen shot 2017-04-25 at 17 59 27](https://cloud.githubusercontent.com/assets/4050585/25409678/f3fdb2e0-29e0-11e7-9e09-4605f8eca785.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.34
