### ISSUE TITLE
CRASH: opening OMERO dataset

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#244]
BEHAVIOR
Launched, opened Image Browser, open OMEGA benchmarking, attempted to open DS ID 1201
CRASH

# 2017-04-26_11-01-08
Exception in thread: OmeroBrowerPanelImageLoader
omero.InternalException : null
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
java.lang.Class.newInstance(Class.java:442)
IceInternal.BasicStream.createUserException(BasicStream.java:2615)
IceInternal.BasicStream.access$300(BasicStream.java:12)
IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099)
IceInternal.BasicStream.throwException(BasicStream.java:2077)
IceInternal.Outgoing.throwUserException(Outgoing.java:538)
omero.api._ThumbnailStoreDelM.getThumbnailByLongestSideSet(_ThumbnailStoreDelM.java:566)
omero.api.ThumbnailStorePrxHelper.getThumbnailByLongestSideSet(ThumbnailStorePrxHelper.java:2342)
omero.api.ThumbnailStorePrxHelper.getThumbnailByLongestSideSet(ThumbnailStorePrxHelper.java:2314)
edu.umassmed.omega.omero.commons.OmeroGateway.getThumbnailSet(OmeroGateway.java:517)
edu.umassmed.omega.omero.commons.runnable.OmeroBrowerPanelImageLoader.run(OmeroBrowerPanelImageLoader.java:133)
java.lang.Thread.run(Thread.java:748)

**Comment by Akramhar** [comment]
cannot reproduce the error, need more details

**Comment by Akramhar** [comment]
should be solved in omega-0.34
