### ISSUE TITLE
TrajectorySegmentation: Unsaved segmentation displays particles should display trjectories on SideBar

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#245]
In TS when Unsaved segmentation is selected in the top data selector side bar should display Default segmentation run.
Currently displays particles even though the SideBar selector indicates that Segmented Tracks are displayed.

**Comment by strambc** [comment]
This behavior does not apply to TE

**Comment by Akramhar** [comment]
The problem is present with TE too but it doesn't show as often because of a workaround in code.

**Comment by Akramhar** [comment]
This should be solved in omega-0.34
