### ISSUE TITLE
TrackEditor: when trajectory is split the trajectory order on the TB becomes alphanumeric

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#246]
When a trajectory is split, the display order on the TB in Unsaved relinking run is alphanumeric instead of numeric.
So for example if Traj_2 is split, then in the Unsaved relinking the portions of Traj_2 (2.1 and 2.2) appear after Traj_19 and before Traj_20.

In addition there appears to be a duplications of trajectories tracts is the same trajectory is split twice by mistake (see screen shot)

![screen shot 2017-04-27 at 18 37 42](https://cloud.githubusercontent.com/assets/4050585/25507204/a5a496ba-2b78-11e7-8db9-17aa2584eb95.png)

**Comment by strambc** [comment]
OBSERVATION: problem persists when Editing run is saved.

**Comment by Akramhar** [comment]
> In addition there appears to be a duplications of trajectories tracts is the same trajectory is split twice by mistake (see screen shot)

I need that you elaborate more this part so that I can reproduce this error.

**Comment by Akramhar** [comment]
The ordering part should be solved in omega-0.34

**Comment by Akramhar** [comment]
I found the duplication issue. Should be solved in omega-0.34
