### ISSUE TITLE
OMEGATrackingMeasures: all plugins windows resizing issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#247]
Inherits from #173
In all TMeas plugins the legend windows are dominant over the graph windows causing squeezing and distortions (see attached screen shot).

![0294add4-0355-11e7-8189-84b73ab6aca4](https://cloud.githubusercontent.com/assets/4050585/25543033/f0702402-2c22-11e7-84da-c59a8ac4b490.png)

**Comment by strambc** [comment]
@Akramhar This is still very much a problem

**Comment by Akramhar** [comment]
This may be solved in omega-0.39.
Needs to be tested a lot.
