### ISSUE TITLE
ParticleDetection+Linking+SNR: faulty +/- queue buttons 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#252]
# EXPECTED BEHAVIOR:
Select parent folder item + green button should be activated
Select executed daughter run both buttons should be greyed
Select queued run: red - button should be activate to permit removal

# INSTEAD:
## In PD
when a queued run is selected the proper parameters are displayed and the - button gets activated. However, when the parent image  is selected to add a second run to the queue the - red button does not go away and it is impossible to add a second run definition. 
Correctly, when the parent image is selected the both buttons are greyed as they should be.

## In PL
when a queued run is selected the proper parameters are displayed and the - button gets activated. However, when the parent PD run  is selected to add a second run to the queue the - red button does not go away and it is impossible to add a second run definition. 
Conversely, when the previous executed PD run is selected the + appears again.
It should appear when the parent folder is selected but not when a previous run is selected (in that case both buttons should be greyed)

## In SNR
the red - button does not appear and the run cannot be discarded.
The green + button is present in all cases.

**Comment by Akramhar** [comment]
should be solved in omega-0.34

**Comment by strambc** [comment]
OBSERVATIONS:
1) PD and PL --> FIXED = works as expected.
RED button works and removes queued run.

2) SNR --> RED/GREEN button behavior fixed
RED button does not work.
Open a new issue about point 2) --> #260
