### ISSUE TITLE
SNREstimation: CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#253]
# BEHAVIOR
1 image loaded >> VIRUS snr 7 density low_Trajectory 113.tif
3 PD run
Launch SNREstimation
CRASH
When tried to run again the information about the OMERO server has been wiped

# LOG
# 2017-05-02_03-16-10
Exception in core
Exception in thread: Thread-1274
omero.ResourceError : null
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
java.lang.Class.newInstance(Class.java:442)
IceInternal.BasicStream.createUserException(BasicStream.java:2615)
IceInternal.BasicStream.access$300(BasicStream.java:12)
IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099)
IceInternal.BasicStream.throwException(BasicStream.java:2077)
IceInternal.Outgoing.throwUserException(Outgoing.java:538)
omero.api._RawPixelsStoreDelM.setPixelsId(_RawPixelsStoreDelM.java:1616)
omero.api.RawPixelsStorePrxHelper.setPixelsId(RawPixelsStorePrxHelper.java:7843)
omero.api.RawPixelsStorePrxHelper.setPixelsId(RawPixelsStorePrxHelper.java:7803)
edu.umassmed.omega.omero.commons.OmeroGateway.getByteWidth(OmeroGateway.java:551)
edu.umassmed.omega.snrSbalzariniPlugin.runnable.SNREstimator.run(SNREstimator.java:125)
java.lang.Thread.run(Thread.java:748)

**Comment by strambc** [comment]
Related with #217 ?

**Comment by Akramhar** [comment]
should be solved in omega-0.34
#217 and this don't seems to be related
