### ISSUE TITLE
General: ID when not saved in OMEGA DB should not be -1

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#254]
In all cases when an item has not been assigned an unique ID because it has not been saved to DB yet the ID should not be -1.

IDEALLY instead of -1 one should have N.A. (= not available)

**Comment by Akramhar** [comment]
There is already an issue on this: #81

**Comment by Akramhar** [comment]
Every ID is initialized to -1 and showed as is. Should be changed that every ID that is -1 is **displayed** as something else ("-" or "n.d.")

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
This issue is solved.
However now the IMAGE ID, which is coming from OMERO, is also listed as NA and the Image Owner is listed as Blank.
Is this correct?
Opened a new issue to describe this new question.
Issue Nr. #289
