### ISSUE TITLE
PD results table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#256]
# Results summary

- [x] ParticlesDetectionRun ID --> Detection Run ID
- [x] Mean spots found per time point --> Average number of spots found per time point
- [x] Z-section to analyze --> Analyzed Z-plane
- [x] Channel to analyze --> Analyzed Channel

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY ARE SHOWN]**)

# Results table
- [x] **ID --> when not available change -1 --> NA**

- [x] Column order should be: ID, Time point, X, Y, Z, C, m0, m1, m2, m3, m4, (NPscore)
- [x] Z column is missing.
- [x] C column should be added.
- [x] NPscore column is missing (not sure if this belongs to PD or PL)

(see screen shot and #257)

![screen shot 2017-05-02 at 17 45 14](https://cloud.githubusercontent.com/assets/4050585/25640816/22d65710-2f5f-11e7-9d14-5c599d9f400d.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
Issues that are not checked off are to be addressed.

**Comment by strambc** [comment]
# Remaining issues

- [ ] All issues that are not checked marked above
- [ ] Yellow hover tooltips for columns from m0 owards are wrong!

**Comment by Akramhar** [comment]
should be fixed in omega-0.36
in case something is left out, close this issue and open a new one
