### ISSUE TITLE
TB: faulty selection of trajectory on TB and faulty synch with SideBar

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#258]
This inherits from #228 and also from #242 

# TE and TS TB
## Selection from SideBar

- [x] 1) When selection is initiated from SideBar selection correctly reflects on the TB. 
- [x] 2) Last selection from SideBar persists and cannot be changed even by clicking elsewhere on image.

## Selection from TB

- [x] 3) When selection is initiated from TB it does not reflect on SideBar.
- [x] 4) Last selection from SideBar persists and cannot be changed even by deselecting on TB

# TMeas TB
- [x] Behavior 1) above does not apply here --> selection from TB and from SideBar works fine and it sync well between the two view.
- [x] Behavior 2) is observed also here --> deselection of last selected trajectory on SideBar does not work also here
- [ ] Behavior 3) When trajectories are selected on the TMeas TB (i.e. Diffusivity) the selection persists on the image on the Side Bar even when the selection is altered in the TB in a different plugin.
For example behavior appeared when the TS plugin was opened and attempt was made to select a different trajectory from a different PL run

**Comment by Akramhar** [comment]
should be solved in omega-0.35

**Comment by strambc** [comment]
# Remaining issues
Moved to a new open issue --> #298
