### ISSUE TITLE
OMEGA: issues remaining in plugin/algorithm descriptions

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#263]
Inherits from #99

All revisions are described here and in text files found --> https://www.dropbox.com/sh/800x9hz78c48qbg/AABbJXlgTNh_TV0JcPYuEG7ca?dl=0

In general the Algorithm Information window is too small so the Algorithm Information description text is often truncated and not visible.

# Particle Detection
Plugin header text: MOSAIC 2D Particle Detector --> MOSAIC 2D Particle Detection
Algorithm Information general:
Name: MOSAIC 2D Particle Detector --> MOSAIC feature point detection
Author: I. F. Sbalzarini --> I. F. Sbalzarini and P. Koumoutsakos
Version: 1.0 --> 1.0.3
Reference: NOT VISIBLE (window too small)
Algorithm Information description: NOT VISIBLE (window too small)

**Comment by strambc** [comment]
# Particle Linking
Algorithm Information general:
Name: MOSAIC 2D Particle Linking--> MOSAIC feature point tracker
Author: I. F. Sbalzarini --> I. F. Sbalzarini and P. Koumoutsakos
Version: 1.0 --> 1.0.3
Reference: NOT VISIBLE (window too small)
Algorithm Information description: NOT VISIBLE (window too small)

**Comment by strambc** [comment]
# SNR Estimation
Algorithm Information description: NOT VISIBLE (window too small)
-->
Algorithm Information description:
This algorithm estimates the local signal to noise ratio (SNR) associated with each bright spot identified and localized during particle detection. It utilizes particle coordinates estimated by the spot detection algorithm and intensities from associated image-planes to extract intensity values and estimate background, noise and SNR associated with the area immediately surrounding each bright spot. Specifically, the algorithm first determines the global background and noise associated with the entire image plane where each particle is localized. It then utilizes the particle size as defined by the user to draw a square area around each particle’s centroid and identify the brightest pixel within the particle area. Finally it estimates local noise, background and SNR based on the Bhattacharya Poisson, the Bhattacharya Gaussian and the Cheezum SNR models. After calculating local SNR values, the algorithm returns aggregate SNR values at the trajectory, plane and image level.

**Comment by strambc** [comment]
# Trajectory Editor
Plugin description:
This is the default Trajectory Editor plugin provided by OMEGA. It utilizes the Trajectory
Browser graphical user interface to facilitate the visualization and selection of individual trajectories and their inspection in the context of the image of origin. Once selected, the plugin allows to edit individual links when necessary.
Algorithm information description: NOT VISIBLE (window too small)

**Comment by strambc** [comment]
#Trajectory Segmentation
 Algorithm information description: NOT VISIBLE (window too small)

**Comment by strambc** [comment]
# Intensity Measures
Plugin button text: Omega Intensity Measures --> Omega IM
Plugin header text: Omega IM -->Omega Intensity Measures

**Comment by strambc** [comment]
# Mobility Measures 
Plugin description:
This is the default OMEGA plugin to estimate and plot mobility measures associated with identified trajectories. It utilizes the Trajectory Browser graphical user interface to facilitate the visualization and selection of individual trajectories to be subjected to analysis.

**Comment by strambc** [comment]
# Velocity Measures
Plugin description:
This is the default OMEGA plugin to estimate and plot velocity measures associated with identified trajectories. It utilizes the Trajectory Browser graphical user interface to facilitate the visualization and selection of individual trajectories to be subjected to analysis.

**Comment by strambc** [comment]
# Diffusivity Measures
Plugin description:
This is the default OMEGA plugin to perform diffusivity analysis on identified trajectories. It utilizes the Trajectory Browser graphical user interface to facilitate the visualization and selection of individual trajectories to be subjected to analysis. Results can then be used to classify trajectories on the basis of their motion type characteristics.
Algorithm Information description:
This algorithm implements diffusivity measurements as described by Ewers et al. (in: Ewers, H., A.E. Smith, I.F. Sbalzarini, H. Lilie, P. Koumoutsakos, and A. Helenius. 2005. Single-particle tracking of murine polyoma virus-like particles on live cells and artificial membranes. Proc Natl Acad Sci USA. 102:15110–15115. doi:10.1073/pnas.0504407102). In addition, it provides an easy to use graphical user interface to plot such measures for each individual trajectory. Finally it utilizes a scatter plot to summarize the data and display the observed diffusion constant (ODC2) and the slope of the moment scaling spectrum (SMSS) of all trajectories in a dataset in a single plot. Individual trajectories are represented as single points in this ODC2 vs. SMSS phase space, allowing to globally evaluate the behavior of "clouds" of trajectories and compare the effect of different experimental conditions on their shapes.

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
Please refer to #296 for remaining open issues
