### ISSUE TITLE
SNR results summary and table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#264]
# Results summary

- [x] SNRRun ID --> SNR Estimation Run ID
- [x] Add --> Analyzed Z-plane --> CURRENTLY ADDED BUT WRONG  (Z-plane analyzed)
- [x] Add --> Analyzed Channel  --> CURRENTLY ADDED BUT WRONG  (Channel analyzed)

- [x] **ID --> when not available change -1 --> NA**
- [x] **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY ARE SHOWN]**)

# Results table
- [x] **ID --> when not available change -1 --> NA**

## ROI Results
- [x] Column headers names and order should be: ID, Time point, X, Y, Z, C, Centroid Intensity, Peak Intensity, Mean Intensity, Local Background, Local Noise, Local SNR, Particle Area

- [x] Z column should be added.
- [x] C column should be added.

## Plane Results

- [x] Column headers names and order should be: ID, Time point, Avg. Centroid Intensity, Avg. Peak Intensity, Avg. Mean Intensity, Background, Noise, Avg. SNR, Min SNR, Max SNR

## Image Results
- [x] Column headers names and order should be: ID, Z, C, Avg. Centroid Intensity, Avg. Peak Intensity, Avg. Mean Intensity, Background, Noise, Avg. SNR, Min SNR, Max SNR

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
All issues solved except -->

- [ ] Add --> Analyzed Z-plane --> CURRENTLY ADDED BUT WRONG  (Z-plane analyzed)
- [ ] Add --> Analyzed Channel  --> CURRENTLY ADDED BUT WRONG  (Channel analyzed)

**Comment by Akramhar** [comment]
should be fixed in omega-0.36
in case something is still wrong, close this issue and open a new one
