### ISSUE TITLE
TE results summary and table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#265]
# Results summary
TrajectoriesRelinkingRun ID --> Editing Run ID
Algorithm: Omega default relinking --> OMEGA Trajectory Editor
Tracks --> Total number of trajectories

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY IS SHOWN]**)

# Results table
- [x] **ID --> when not available change -1 --> NA**

- [x] Column order should be: Particle ID, Trajectory ID, Trajectory name, Time point, X, Y, Z, C

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by Akramhar** [comment]
>Algorithm: Omega default relinking --> OMEGA Trajectory Editor

This needs to be reviewed when we have time because there is a issue here.

**Comment by strambc** [comment]
Remaining issue to be addressed
- [ ] Column order should be: Particle ID, Trajectory ID (is now Track ID), Trajectory name (is now Track Name), Time point, X, Y, Z, C

**Comment by Akramhar** [comment]
I think we talked about this but I may remember wrong:
the way the table is built "Particle ID" and the Values are created together.
after the track information are added.
btw this is the same order used in Linking.
to change this I would need to change the whole process of creating results.
If it's not absolutely necessary I would avoid this for the present time.

**Comment by Akramhar** [comment]
I changed track to trajectory in the meantime

**Comment by Akramhar** [comment]
I added track length

**Comment by Akramhar** [comment]
if there are more issues please close this one and open a new one
