### ISSUE TITLE
General label changes for consistency

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#266]
# General menu bar
 - [x] SNR Estimator --> SNR Estimation

# Data Browser

- [x] Tab labels: Other --> Quality control

- Column labels:
- [x] S N R --> SNR Estimation
- [x] Trajectories Relinking --> Trajectory Editing
- [x] Trajectories Segmentation --> Trajectory Segmentation

# SideBar
## View Options tab

- [x] Z sections --> Z-section
- [x] Timepoints (Time) --> Time point (Time)
- [x] Channels --> Channel

## Tracks tab

- [x] Tab label: Tracks --> Trajectories
- [x] Check boxes labels: Tracks --> Trajectories
- [x] Select Overlay To Display selector:
- [x] Tracks --> Trajectories
- [x] Relinked Tracks --> Edited trajectories
- [x] Segmented Tracks --> Segmented trajectories

# Run names on General data selector and SideBar selector + Data Browser

- [ ] - YYYY-MM-DD_XX-XX-XX_MOSAIC 2D SNR Estimation --> YYYY-MM-DD_XX-XX-XX_MOSAIC SE run
- [ ] - YYYY-MM-DD_XX-XX-XX_MOSAIC 2D Particle Detector --> YYYY-MM-DD_XX-XX-XX_MOSAIC 2D PD run
- [ ] - YYYY-MM-DD_XX-XX-XX_MOSAIC 2D Particle Linking --> YYYY-MM-DD_XX-XX-XX_MOSAIC 2D PL run
- [ ] - YYYY-MM-DD_XX-XX-XX_Default relinking run --> YYYY-MM-DD_XX-XX-XX_default OMEGA TE run
- [ ] - Unsaved relinking --> Unsaved Editing
- [ ] - YYYY-MM-DD_XX-XX-XX_Default segmentation run --> YYYY-MM-DD_XX-XX-XX_default OMEGA TS run
- [ ] - Unsaved segmentaion --> Unsaved Segmentation
- [ ] - YYYY-MM-DD_XX-XX-XX_Omega default intensity run --> YYYY-MM-DD_XX-XX-XX_default OMEGA IM run

** SAME FOR ALL OTHER Tracking Measures runs **

# TE

- [ ] Tab label: Editor --> Editing

# Tracking Measures general

- [x] Tab label: Graphs --> Plots
- [x] Select Independent Variable (x axis) menu label: Track --> Trajectory
- [x] Plot x axis label: Track --> Trajectory

### Run tab

- [x] Check box label: Enable SNR estimation --> Enable SNR Estimation
- [x] Selector label: Select SNR estimation --> Select SNR Estimation Run

### Run tab

- [x] Selector label: Window size --> Maximum computation window size

- Combo box items:
- [x] 3 --> L/3
- [x] 5 --> L/5
- [x] 10 --> L/10

- [x] Selector label: Log option --> ODC estimation method: 
- [ ] Combo box items:
- [ ] Log only --> Log-log
- [ ] Lin only --> Linear
- [ ] Log and Linear --> Linear and Log-log
- [x] Selector label: Select SNR estimation --> Select SNR Estimation Run

## Local results

- [x] Tab label: Local results --> Moments of Displacement vs. delta t plots results

## Global results Gamma

- [x] Tab label: Global results Gamma --> Moment Scaling Spectrum results

## Global results D & SMSS

- [x] Tab label: Global results D & SMSS --> Phase space results

**Comment by Akramhar** [comment]
should be fixed in omega-0.35 apart from the image part as asked here #272

**Comment by strambc** [comment]
Several are still not done.
