### ISSUE TITLE
TS results summary and table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#267]
# Results summary
TrajectoriesSegmentationRun ID --> Segmentation Run ID
Algorithm: Omega default segmentation --> OMEGA Trajectory Segmentation
Tracks --> Total number of trajectories
Segments total --> Total number of segments
Mean segments per track --> Average number of segments per trajectory

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY IS SHOWN]**)

# Results table

- [x] **ID --> when not available change -1 --> NA**

- [x] Column order should be: ID, Trajectory name, Time point, X, Y, Z, C, Segment name, Motion type

**Comment by Akramhar** [comment]
this should be fixed in omega-0.35.
the difference in the column order is due to the fact that columns are generated in blocks ( particles / tracks / segments ).
If the order is such a huge problem it can be fixed but requires work

**Comment by strambc** [comment]
## Remaining issue

 - [ ] Column order should be: Particle ID, Trajectory ID (is now Track ID), Trajectory Name (is now Track Name), Frame, X, Y, Z, C, Segment ID, Segment Name, Motion Type (it is now Segment Type)

**Comment by Akramhar** [comment]
same answer I gave to #265, in the meantime I fixed the labels

**Comment by Akramhar** [comment]
I added track length
