### ISSUE TITLE
IM results summary and table revision 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#269]
# Results summary

- [x] TrackingMeasuresIntensityRun ID --> Intensity Measures Run ID
- [x] Algorithm: Omega default intensity --> OMEGA Intensity Measures

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY IS SHOWN]**)

# Results table
## Local results
**TAB IS MISSING** 
--> **SHOULD WE HAVE SOME OF IT HERE OR ALL IN SNR?**

## Global results
- [x] **ID --> when not available change -1 --> NA**

**ID column is missing**

- [x] Column order should be: ID, Trajectory name, Segment name, Length, Motion type,  Avg. Centroid Intensity, Min Centroid Intensity, Max Centroid Intensity, Avg. Peak Intensity, Min Peak Intensity, Max Peak Intensity, Avg. Mean Intensity, Min Mean Intensity, Max Mean Intensity, Avg. Local  Background, Min Local  Background, Max Local Background, Avg. Local  Noise, Min Local  Noise, Max Local Noise, Avg. Local  SNR, Min Local  SNR, Max Local  SNR

## Image results
Column headers names and order should be: ID, T, Z, C, Avg. Centroid Intensity, Avg. Peak Intensity, Avg. Mean Intensity, Background, Noise, Avg. SNR, Min SNR, Max SNR,

**Comment by Akramhar** [comment]
Image results cannot be displayed here because all the values are related to segments.
Local results should not be displayed because they are not computed: they should be displayed in the detection / snr views

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
Where do you want to put the IMAGE level results?
They have to be somewhere.

**Comment by Akramhar** [comment]
most of the plane / image level results have been added to the SNR as per #264

**Comment by strambc** [comment]
# Remaining issue

- [ ] Column order should be: Trajectory ID, Trajectory Name, Segment ID, Segment Name, Length, Motion Type
- [ ] Length and Motion Type are missing
- [ ] Yellow hover tooltips for columns from Avg.Mean Intensity owards are wrong!

**Comment by Akramhar** [comment]
same answer I gave to #265 regarding column order, in the meantime I fixed the labels and added track and segment length. Tooltips should be fixed too.

**Comment by Akramhar** [comment]
if there are more issues please close this one and open a new one
