### ISSUE TITLE
VM results summary and table revision 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#270]
# Results summary

- [x] TrackingMeasuresVelocityRun ID --> Velocity Measures Run ID
- [x] Algorithm: Omega default intensity --> OMEGA Velocity Measures

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY IS SHOWN]**)

# Results table
## Local results

 - [x] **ID --> when not available change -1 --> NA**

- [x] Column order should be: ID, Trajectory name, Segment name, Motion type, Time point, X, Y, Z, C, Instantaneous Speed, Instantaneous Cum. Curv. Speed, Instantaneous Cum. Straight Speed

## Global results
- [x] **ID --> when not available change -1 --> NA**

**ID column is missing**
- [x] Column order should be: ID, Trajectory name, Segment name, Length, Motion type, Avg. Curv. Speed, Avg. Straight Speed, Forward Progression Linearity

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
# Remaining issues
- [ ] Algorithm: OMEGA Deault Velocity Measures--> OMEGA Velocity Measures

**Comment by Akramhar** [comment]
same answer I gave to #265 regarding column order, in the meantime I fixed the labels and added track and segment length

**Comment by Akramhar** [comment]
if there are more issues please close this one and open a new one
