### ISSUE TITLE
MM results summary and table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#271]
# Results summary

- [x] TrackingMeasuresMobilityRun ID --> Mobility Measures Run ID
- [x] Algorithm: Omega default mobility --> OMEGA Mobility Measures

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY IS SHOWN]**)

# Results table
## Local results

 - [x] **ID --> when not available change -1 --> NA**

- [x] Column order should be: ID, Trajectory name, Segment name, Motion type, Time point, X, Y, Z, C, Distance Traveled, Cum. Curv. Distance Traveled, Cum. Straight Distance Traveled, Cum. Confinement Ratio, Instantaneous Angle, Dir. Change, Cum. Time Traveled

## Global results
- [x] **ID --> when not available change -1 --> NA**

**ID column is missing**

- [x] Column order should be: ID, Trajectory name, Segment name, Length, Motion type, Tot. Curv. Distance Traveled, Max Cum. Straight Distance Traveled, Tot. Net Straight Distance Traveled, Confinement Ratio, Tot. Time Traveled

**Comment by Akramhar** [comment]
just to be sure:
- Max Cumulative Straight Distance Traveled was Max Displacement before?
- Tot. Net Straight Distance Traveled was Cumulative Straight-Line Distance?
- Tot. Curv. Distance Traveled was Cumulative Curvilinear Distance?

Its kinda of difficult because it seems you put new names and shuffle the order at the same time.

anyway it should be fixed in omega-0.35, if the above is correct

**Comment by strambc** [comment]
Did not think i had changed names with respect to the latest revision we did.
I will double check because if i did i did not mean to.

Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 13 Jun 2017, at 07:42, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


just to be sure:

  *   Max Cumulative Straight Distance Traveled was Max Displacement before?
  *   Tot. Net Straight Distance Traveled was Cumulative Straight-Line Distance?
  *   Tot. Curv. Distance Traveled was Cumulative Curvilinear Distance?

Its kinda of difficult because it seems you put new names and shuffle the order at the same time.

anyway it should be fixed in omega-0.35, if the above is correct

**Comment by strambc** [comment]
The names I used are the ones that were  proposed in the 2017-03-24 revision:

[2017-03-24_Tacking Measures_menu labels verification_V04.xlsx](https://github.com/OmegaProject/Omega/files/1075050/2017-03-24_Tacking.Measures_menu.labels.verification_V04.xlsx)

**Comment by strambc** [comment]
In addition the menu items were further verified as per issue #262

[2017-05-08_Tacking Measures_menu labels verification_V06_tested.xlsx](https://github.com/OmegaProject/Omega/files/1075147/2017-05-08_Tacking.Measures_menu.labels.verification_V06_tested.xlsx)

**Comment by strambc** [comment]
In summary:

- MaxCumStraightDistTraveled
Full name --> Max Cumulative Straight-Line Distance Traveled 	
Was --> Max Displacement

- TotalNetStraightDistTraveled
Full name --> Total Net Straight-Line Distance Traveled 	
Was --> Total Net Displacement

- TotalCurvDistTraveled
Full name -->Total Curvilinear Distance Traveled	
Was --> Total Distance Traveled

**Comment by Akramhar** [comment]
Ok understood, I have to recheck everything with #262 to be sure column names are matching menu items

**Comment by strambc** [comment]
# Remaining issue
- [ ] Column order should be: Trajectory ID (is now Track ID), Trajectory Name (is now Track Name), Segment ID, Segment Name, Length, Motion Type (it is now Segment Type), REMAINING COLUMNS ARE FINE
- [ ] Length is missing

**Comment by Akramhar** [comment]
same answer I gave to #265 regarding column order, in the meantime I fixed the labels and added track and segment length

**Comment by Akramhar** [comment]
if there are more issues please close this one and open a new one
