### ISSUE TITLE
DM results summary and table revision

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#272]
# Results summary
TrackingMeasuresDiffusivityRun ID --> Diffusivity Measures Run ID
Algorithm: Omega default diffusivity --> OMEGA Diffusivity Measures

- [x] **ID --> when not available change -1 --> NA**
- [x]  **Make sure Algorithm Information contains the correct information (see #263)** 
- [x] **[APPLIES WHERE EVER SUMMARY IS SHOWN]**)

# Results table
## Local results

 - [x] **ID --> when not available change -1 --> NA**

Column order should be: ID, Trajectory name, Segment name, Motion type, Max Calc. Window,  
Moment's Order (Nu), Delta t, Moment of Displacement (Mu), Log Delta t, Log Moment of Displacement
**REMOVE --> Interval (or clarify what it is)**

## Global results Gamma
- [x] **ID --> when not available change -1 --> NA**

**ID column is missing**
Column order should be: ID, Trajectory name, Segment name, Motion type, Length, Max Calc. Window,  Moment's Order (Nu), Slope (Gamma), Intercept (y0), ODC
**REMOVE --> ALL OTHER COLUMNS (or clarify what they are)**

## Global results ODC and SMSS
Column order should be: ID, Trajectory name, Segment name, Motion type, Length, Max Calc. Window, Slope Log-Log MSD, Intercept (y02), ODC2, Slope MSS, Uncertainty ODC2, Uncertainty SMSS

## Image results
Column headers names and order should be: ID, T, Z, C, Minimum Detectable ODC2

**Comment by Akramhar** [comment]
what do you mean by Max Calc. Window? What value should be displayed here ?

**Comment by Akramhar** [comment]
same question about Length

**Comment by Akramhar** [comment]
what does Image results mean? all these values are segment based, what should i do here?

**Comment by Akramhar** [comment]
apart from questions above, everything else is fixed in omega-0.35

**Comment by strambc** [comment]
## Max. Cal. Window 

--> refers to the maximum size of the window that is used to calculate the diffusivity measures. For example in case of divisor value 3 the max size of the window is L/3, when the divisor value is 10 the max size of the window is L/10. 
This means that all intervals sizes ∆n = (1, 2, 3 --> L/10)  are used to calculate the moments and for each value the average of the obtained results are plotted.

The idea is that in this column we will have L/3, L/5 or L/10.

The name is not very clear I admit: what about Max Calc. Window Size or Max Calculation WIndow Size instead?


We have been using three values

**Comment by strambc** [comment]
Max Cal. Window and Length are both supposed to be here to facilitate data export for users.
They are both important information to have and I argue they should be added here as well.

**Comment by strambc** [comment]
# Image results

--> refers to the Min Detectable ODC2 which is a image-level value and should be reported to the user somewhere.
That is why I added an extra tab which parallels the SNR precedent

**Comment by Akramhar** [comment]
So:
1) Max Calculation Windows: added
2) Length: atm is not exposed
3) Min Detectable ODC2: since it would be the only actual data in an Image TAB, i added it in the phase results for each segment. I think a full tab only for 1 data it would be a overwhelming.
