### ISSUE TITLE
TrajectorySegmentation: facilitate identification of segments from same trajectory

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#274]
Have to think of a way for users to highlight segments belonging to same track. For example:

1. the different segments might be connected on the GUI with a dashed line that crosses down from one segment to the next (could be vertical)
2. the group of segments from a single trajectory could be highlighted with a lighter version of the trajectory color either underlying the segment group on the browser or along the side of the browser (where the names are displayed)

**Comment by Akramhar** [comment]
I'm confused: is the dual color that we use now (both track and segment color displayed) not enough to identify them?

**Comment by strambc** [comment]
There are two aspects:

# 1) visualization on the browser
I was thinking it would not be too difficult to have a back ground color on the browser that matches the original trajectory color that underlies all segments that pertain to it. Alternatively a dashed line. Whatever would be easier to implement.

# 2) visualization on the image.
When you are on the image, each segment is painted with its color but separate from the other segments that belong to the trajectory.
I was thinking it would be great to have a way of connecting them visually on the image.
For example with a dashed line that connects them

**Comment by strambc** [comment]
Point 2 was transferred to #284

**Comment by strambc** [comment]
Point 1:
I guess if trajectories can be connected on image this would be a way to postpone the need for 1

**Comment by Akramhar** [comment]
segments are now connected by dotted line, do we still need point one of this ticket?

**Comment by strambc** [comment]
Opened a new issue for point 1 and assigned to  beta 2.0 
 #274
