### ISSUE TITLE
 Omega Diffusivity Measures: SNR Estimation selection issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#275]
This inherits from #237

OBSERVATION:
now the  SNR run is indeed available on TM-Diffusivity Run tab.
However upon first selection of the tab the display behavior is still faulty:
Even if Error disabled is the default selection, the correct available SNR estimation run shows up in the selector despite the fact that it should not.

DESIRED BEHAVIOR:

upon first selection --> Error disabled selected by default, Select SNR estimation --> should be blank 
upon selection of Error option --> Error enabled the available SNR Estimation run should appear

NOTE upon selection of Error option --> Error disabled after Error enabled has been selected once the correct behavior is displayed (see screenshot).
![screen shot 2017-05-05 at 13 35 15](https://cloud.githubusercontent.com/assets/4050585/25757229/b4295e12-3197-11e7-82d0-4952f796ec3a.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.35
