### ISSUE TITLE
ImageBrowser: OMERO browser has wrong settings but connects anyway

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#277]
BEHAVIOR:

the server name in the OMERO Browser window is set to omega.umassmed.edu instead of omero.umassmed.edu

Neverthelsess the connection works.
If one changes the settings to omero... upon the following lunch the settings go back to omega...

![screen shot 2017-05-16 at 10 24 26](https://cloud.githubusercontent.com/assets/4050585/26111021/efe1eb76-3a21-11e7-93ae-d3d58246cbd0.png)

**Comment by Akramhar** [comment]
omero.umassmed.edu is one of the name of the server.
The server can be reached as omega.umassmed.edu or deduve.umassmed.edu

If you don't click the "remember server information" and correctly close the app the new information are not saved.
