### ISSUE TITLE
DataBrowser: selection backward up the chain

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#278]
Selection up the chain in Data Browser is faulty: take a look at the screen shots to see what is going on.
If you need further information let me know.

**Comment by strambc** [comment]
![step 1](https://cloud.githubusercontent.com/assets/4050585/26117746/834b16cc-3a35-11e7-8530-651c4aa0b6fe.png)
![step 2](https://cloud.githubusercontent.com/assets/4050585/26117747/834b3058-3a35-11e7-820b-0bd6107d4ffc.png)
![step 3](https://cloud.githubusercontent.com/assets/4050585/26117751/835b84b2-3a35-11e7-9c6d-2810eea7395e.png)
![step 4](https://cloud.githubusercontent.com/assets/4050585/26117750/83530d00-3a35-11e7-895d-dcd87c5793d5.png)
![step 5](https://cloud.githubusercontent.com/assets/4050585/26117749/8352e00a-3a35-11e7-9457-1d9461f3dd4a.png)
![step 6](https://cloud.githubusercontent.com/assets/4050585/26117748/83529c26-3a35-11e7-8e50-f32d84dc0f22.png)
![step 7](https://cloud.githubusercontent.com/assets/4050585/26117752/836608c4-3a35-11e7-80fe-272c408415b7.png)
![step 8](https://cloud.githubusercontent.com/assets/4050585/26117754/8371c04c-3a35-11e7-8644-6efc6fac9c52.png)
![step 9](https://cloud.githubusercontent.com/assets/4050585/26117753/836e5498-3a35-11e7-90e4-8d11b22d9644.png)
![step 10](https://cloud.githubusercontent.com/assets/4050585/26117755/8375d1d2-3a35-11e7-9de0-425768217031.png)
![step 11](https://cloud.githubusercontent.com/assets/4050585/26117756/8379f884-3a35-11e7-977e-60207df120df.png)

**Comment by Akramhar** [comment]
solved in omega-0.35
