### ISSUE TITLE
DataBrowser: unchecking boxes up the tree CRASH

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#279]
CRASH HAPPENED TWICE.
Upon unchecking up the tree.
Attempting to uncheck image.
_______
## Log CORE
- 2017-05-16_02-59-00	Error loading options
- 2017-05-16_02-59-00	VM options: 
- 2017-05-16_02-59-00	Application started!

## Log GENERAL
- 2017-05-16_02-59-00	Application started!
- 2017-05-16_02-58-38
Exception in thread: TBROIThumbnailLoader
java.lang.reflect.InvocationTargetException : null
java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader.updateStatus(TBROIThumbnailLoader.java:87)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader.run(TBROIThumbnailLoader.java:69)
java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.NullPointerException : null
edu.umassmed.omega.commons.gui.GenericSegmentsBrowserTrajectoriesPanel.loadBufferedImages(GenericSegmentsBrowserTrajectoriesPanel.java:452)
edu.umassmed.omega.commons.gui.GenericSegmentsBrowserPanel.updateMessageStatus(GenericSegmentsBrowserPanel.java:688)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader$1.run(TBROIThumbnailLoader.java:91)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

BROIThumbnailLoader
java.lang.reflect.InvocationTargetException : null
java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader.updateStatus(TBROIThumbnailLoader.java:87)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader.run(TBROIThumbnailLoader.java:69)
java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.NullPointerException : null
edu.umassmed.omega.commons.gui.GenericTrajectoriesBrowserTrajectoriesPanel.loadBufferedImages(GenericTrajectoriesBrowserTrajectoriesPanel.java:369)
edu.umassmed.omega.commons.gui.GenericTrajectoriesBrowserPanel.updateMessageStatus(GenericTrajectoriesBrowserPanel.java:582)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader$1.run(TBROIThumbnailLoader.java:91)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by strambc** [comment]
Another similar case:

# 2017-05-16_05-11-55
Exception in thread: TBROIThumbnailLoader
java.lang.reflect.InvocationTargetException : null
java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader.updateStatus(TBROIThumbnailLoader.java:87)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader.run(TBROIThumbnailLoader.java:69)
java.lang.Thread.run(Thread.java:748)
Caused by: 
java.lang.NullPointerException : null
edu.umassmed.omega.commons.gui.GenericSegmentsBrowserTrajectoriesPanel.loadBufferedImages(GenericSegmentsBrowserTrajectoriesPanel.java:452)
edu.umassmed.omega.commons.gui.GenericSegmentsBrowserPanel.updateMessageStatus(GenericSegmentsBrowserPanel.java:688)
edu.umassmed.omega.commons.runnable.TBROIThumbnailLoader$1.run(TBROIThumbnailLoader.java:91)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

hread.java:82)

**Comment by Akramhar** [comment]
I don't seem to be able to reproduce the problem.
May be fixed due to fix for #280, need to be tested and confirmed again.
In case it happens again I need more specific on how to reproduce.
