### ISSUE TITLE
OMERO browser: image selection and loading issue

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#281]
When images are in the list view.
By default they are ordered by ID
Then they were ordered  based on "Dimensions".
Then two were selected on the reordered set and loaded.
ERROR --> images that got loaded were not the ones selected on the reordered view but the corresponding ones in the default view (see attached screen shots).

**Comment by strambc** [comment]
![screen shot 2017-05-26 at 16 45 14](https://cloud.githubusercontent.com/assets/4050585/26512163/5227e9a2-4233-11e7-8b38-e6be778d0cdd.png)
![screen shot 2017-05-26 at 16 45 34](https://cloud.githubusercontent.com/assets/4050585/26512162/52265e34-4233-11e7-9624-02b86ebdb9fe.png)
![screen shot 2017-05-26 at 16 45 57](https://cloud.githubusercontent.com/assets/4050585/26512161/5224d12c-4233-11e7-8ea2-b415adbe5742.png)
![screen shot 2017-05-26 at 16 46 25](https://cloud.githubusercontent.com/assets/4050585/26512160/52244c48-4233-11e7-808e-2848497d0d38.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
Problem solved
