### ISSUE TITLE
OMEGA Diffusivity Measures: when a trajectory is selected on 1 image, shift to another image does not refresh graph tab

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#282]
![step 1](https://cloud.githubusercontent.com/assets/4050585/26513941/7cf1a048-423c-11e7-9406-84e1d3f0ec4f.png)
![step 2](https://cloud.githubusercontent.com/assets/4050585/26513944/7cf50c9c-423c-11e7-8968-e4a334fe3150.png)
![step 3](https://cloud.githubusercontent.com/assets/4050585/26513942/7cf2c28e-423c-11e7-8f46-ea36a8b82dbc.png)
![step 4](https://cloud.githubusercontent.com/assets/4050585/26513943/7cf2e458-423c-11e7-8a70-418249bbfb5f.png)
![step 5](https://cloud.githubusercontent.com/assets/4050585/26515040/a65c3f62-4244-11e7-9119-156f736d7390.png)

**Comment by strambc** [comment]
Two images loaded.
Single color --> C1-I1_CMMT_7hPT_GagGFP_untreated_01_hstk_CROP2.tif
Two color --> I1_CMMT_7hPT_GagGFP_Cherrytub_untreated_01_hstk_CROP2.tif
PD parameters --> Parameters: 3/3.0/0.1
PL parameters --> Parameters: 10/2/Brownian/1/1/Greedy/25

Trajectory results are identical.
Image 1 trajectory 7 colored Red
Image 2 trajectory 7 colored Blue

Select Image 1, select Trajectory 7 show graph
Change to Image 2 on SideBar
On Browser selection is shifted correctly.
On Graph tab all graphs should be displayed (because no trajectories are selected) instead only the X-Y Trajectory graph is populated

**Comment by Akramhar** [comment]
should be fixed in omega-0.35
