### ISSUE TITLE
TrajectorySegmentation: facilitate identification of segments from same trajectory on image

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#284]
visualization of segments from same trajectory on the SB image.

When you are on the image, each segment is painted with its color but separate from the other segments that belong to the trajectory.
We need to have a way of connecting them visually on the image.
For example with a dashed line that connects them

Inherits point 2 from #274

**Comment by Akramhar** [comment]
should be solved in omega-0.35

**Comment by strambc** [comment]
The connection between segments on the SB image works well now.
However the overall trajectory-selection box is now missing.
The un-segmented trajectory (or default segment) is selected but no box is visible.
This effect is only associated with segments. 
When full trajectories are displayed such as in Editor, the box is showing up fine.

**Comment by strambc** [comment]
NOTE: when a portion of a segmented trajectory has not been assigned a specific motion type, then it does not get highlighted on the image when selected.
The selection happens but BLUE BOXES do not appear around each spot.
The desired behavior is that even UNASSIGNED segments are highlighted on the image
