### ISSUE TITLE
Trajectory Measures: OMEGA DM does not launch

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#286]
All windows detached
All plugins undocked
Image loaded
Particle Detection
Particle Linking
Un-select a number of trajectories 
Change color to 4 remaining trajectories
Attempt to launch OMEGA DM
--> DM does not launch

________
Case description:
I6_CMMT_7hPT_GagGFP_Cherrytub_1htreated_07_hstk_CROP2.tif
Color GFP
PD 3/0.001/0.5
PL 2/5/100

**Comment by strambc** [comment]
This happened also with:
All windows attached
All plugins docked

**Comment by strambc** [comment]
Case description:
see #287

**Comment by Akramhar** [comment]
should be fixed in omega-0.36
