### ISSUE TITLE
Single Particle Tracking: Execute Queue does not launch

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#287]
Set parameters,
Add to ques.
Click on Execute Queue
Queue does not lauch.

This has happened multiple times and usigng mainly two images (see below)
See log below.
_______
Case description:
CASE 1
I6_CMMT_7hPT_GagGFP_Cherrytub_1htreated_07_hstk_CROP2.tif
Color GFP
PD 3/0.001/0.5
PL 2/5/100

CASE 2
Creating 100 SDWorkers for VIRUS snr 7 density low_Trajectory 113.tif
-Radius: 2
-Cutoff: 0.35
-Percentile: 0.1
Mean spots found per time point: 3.86
Max spots found per time point: 8
Min spots found per time point: 2
-Displacement: 10.0
-Link Range: 3
-Movement Type: Brownian
-Object Feature: 1.0
-Dynamics: 1.0
-Optimizer: Greedy
-Min Track Length: 10
Total number of trajectories: 12
Average trajectory length: 21.75
Max trajectory length: 58
Min trajectory length: 13

**Comment by strambc** [comment]
[Log_Plugin_MOSAICfeaturepointdetection.log](https://github.com/OmegaProject/Omega/files/1376868/Log_Plugin_MOSAICfeaturepointdetection.log)

**Comment by strambc** [comment]
Happened again:
# 2017-10-11_03-33-26	Problem in frame 4

# 2017-10-11_03-33-26	Pulling results from SDWorkers

# 2017-10-11_03-33-24	Creating 100 SDWorkers for VIRUS snr 7 density low_Trajectory 113.tif

# 2017-10-11_03-26-40	Application started!

**Comment by Akramhar** [comment]
Seems to be fixed in omega-0.36
