### ISSUE TITLE
OmegaBrowser Times Analyzed counter does not work for PROJECT and DATASET

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#288]
Related to closed issue #112

Times Analyzed should just count the times the data contained in the Dataset and Project (i.e. images) has been used as input for Particle Dectection or SNR.

For example when a Project/Dataset has two images:
The first subjected to 1 PD and 1 PL.
The other subjected to 1PD and 1SNR

the counter should say:
-Project: times analyzed 3
-Dataset: times analyzed 3
-Image1: times analyzed 1
-PD: time analyzed 1
-PL: times analyzed 1 (= the default RE-LINKING RUN)
-TE: times analyzed 1 (= the default SEGMENTATION RUN)
-TS: times analyzed 4 (= the default MOTION ANALYSIS RUNS)

-Image1: times analyzed 2
-PD: times analyzed 0
-SNR: times analyzed 0

**Comment by Akramhar** [comment]
I dont think so, the counter on Project and Dataset should be increased when Project or Dataset wide analysis are done.
Atm we dont have Project / Dataset wide analysis so it could be hidden if you don't like it.

**Comment by Akramhar** [comment]
I can add a different entry in the panel that says: 
Images analyzed ##

**Comment by strambc** [comment]
That is fine.
The label should be

Number of images analyzed:


On Oct 13, 2017, at 11:58, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


I can add a different entry in the panel that says:
Images analyzed ##

**Comment by Akramhar** [comment]
should be fixed in omega-0.36
