### ISSUE TITLE
General: Imported image ID listed as NA and owner missing

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#289]
Inherits in part from closed issue #254
IMAGE ID, which is coming from OMERO, is listed as NA and the Image Owner is  Blank.
Is this correct?
DO NOT THINK SO

**Comment by Akramhar** [comment]
IMAGE ID is NA because the image is not saved in our DB, so that's correct.
Owner I have to verify it put could that seems to be an error.

**Comment by Akramhar** [comment]
should be corrected in omega-0.36
