### ISSUE TITLE
Particle Detection: Run finished but particles do not appear on SideBar

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#291]
Run finished. No particles displayed on Image.
Attempted to select in various ways. Did not respond. Had to relaunch application.

CASE DESCRIPTION: 
two images 
Image 1 "VESICLE snr 7 density low" and 
Image 2 "VIRUS snr 7 density low"
PD Radius 3/Cutoff 3/Percentile 0.1
No PL run

**Comment by strambc** [comment]
![issue 291_problem_1_step1](https://user-images.githubusercontent.com/4050585/31510489-b89d6842-af52-11e7-8d57-69ccd5db3de6.png)

**Comment by strambc** [comment]
Nothing of notice on Log

- 2017-10-12_01-32-30	Pulling results from SDWorkers
- 2017-10-12_01-32-24	Creating 100 SDWorkers for VESICLE snr 7 density low_tSr.tif
- 2017-10-12_01-30-11	Application started!

**Comment by strambc** [comment]
Attempted to relaunch and do exact same thing and application CRASHED.
Log report was exactly the same as the one reported above
[Log_Plugin_MOSAICfeaturepointdetection.log](https://github.com/OmegaProject/Omega/files/1380156/Log_Plugin_MOSAICfeaturepointdetection.log)

**Comment by strambc** [comment]
Repteated same behavior with same images three times.

**Comment by strambc** [comment]
Tried with 1 single image.
VIRUS snr 7 density low_Trajectory 113.tif
PD 2/0.35/0.1
Worked as expected.

**Comment by Akramhar** [comment]
this problem is probable related to #287, needs to be checked on omega-0.36 to see if it happens again

**Comment by strambc** [comment]
Problem solved.
It is likely related to change in parametrization of algorithm.
The problem happened while I was in the process of testing #233
The settings I was using when I opened that issue do not work any more.
Issue was opened In April with version v033.
Has the MOSAIC version been changed since then?

**Comment by strambc** [comment]
Problem is likely related to change in parametrization of algorithm.
The problem happened while I was in the process of testing #233<https://github.com/OmegaProject/Omega/issues/233>
The settings I was using when I opened that issue do not work any more.
Issue was opened In April with version v033.
Has the MOSAIC version been changed since then?

On Oct 12, 2017, at 13:55, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


this problem is probable related to #287<https://github.com/OmegaProject/Omega/issues/287>, needs to be checked on omega-0.36 to see if it happens again

**Comment by Akramhar** [comment]
Yes it has. That could be too but still the app shouldnt crash because of parameters

**Comment by strambc** [comment]
Let's test when new version comes out.

**Comment by Akramhar** [comment]
Everything works correctly, the results produced do not contain any particle due to parametrization
