### ISSUE TITLE
OMEGA: issues remaining in plugin/algorithm descriptions _ UPDATED

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#296]
Inherits from #263

**Comment by strambc** [comment]
All revisions are described here and in text files found --> https://www.dropbox.com/sh/800x9hz78c48qbg/AABbJXlgTNh_TV0JcPYuEG7ca?dl=0

**Comment by strambc** [comment]
# Particle Detection
## Remaining issues
Plugin header text: MOSAIC 2D Particle Detector --> MOSAIC 2D Particle Detection
Algorithm Information general:
Algorithm Information description: IT IS NOW BLANK

**Comment by strambc** [comment]
# Particle Linking
## Remaining issues
Plugin header text: MOSAIC feature point tracker --> MOSAIC 2D Particle Detection
Plugin button short label: MOASIC FPT --> MOSAIC PT
Algorithm Information general:
Algorithm Information description: IT IS NOW BLANK

**Comment by strambc** [comment]
# SNR Estimation
CLOSED

**Comment by strambc** [comment]
# Trajectory Editor
Plugin window algortithm description --> CLOSED
HOWEVER --> Plugin window header bar still says "OMEGA Trajectory Editor" and it should "OMEGA Trajectory Editing" 
see also #266

**Comment by strambc** [comment]
# Trajectory Segmentation
Plugin window algortithm description --> CLOSED

**Comment by strambc** [comment]
# Intensity Measures
Plugin window algortithm description --> CLOSED

**Comment by Akramhar** [comment]
1) Particle detection
current header says: MOSAIC feature point detection
hence the button that says MOSAIC FPD

2) Particle Linking
current header says MOSAIC feature point tracker
hence the button that says MOSAIC FPT

--so you want to change both of them again?

Description is currently visible...maybe its a mac problem? Or are you referring to something else? See pics below.
![untitled](https://user-images.githubusercontent.com/3996749/31557975-19553a5e-b019-11e7-98fb-8d4e6bb6f97e.png)

**Comment by Akramhar** [comment]
Ah, I think I understand the confusion: you are referring to the header as if it different from algorithm name.

The name of the algorithm is automatically the name of the plugin and the header bar.
They all refer to the same string.

If you want to have 2/3 different name the whole system needs to be changed.

**Comment by Akramhar** [comment]
naming should be fixed in omega-0.36
for data browser I used the naming convention we established for Element Information Panel instead of the one written here since the whole naming was already implemented.
Let me know if that's fine
