### ISSUE TITLE
Tracking Measures TB: faulty synch with TE and TS TB

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#298]
This inherits partially from remaining issue on #258

**Comment by strambc** [comment]
- [ ] 1) when selecting segments no boxes appear (described in  Remaining issues from #284)
- [ ] 2) synch between the TB of Tracking Measures on one hand and the TB of TS and TE on the other is faulty in both direction --> selection originated in one side does not synch with the other side
NOTE --> synch between different open Tracking Measures TB (e.g. IM and MM) works fine

**Comment by Akramhar** [comment]
1) Now the selection box for segments should work correctly.
I had to do some serious modification so needs to be tested properly.

2) TB of Tracking Measures and TB of TS and TE now should work properly in both direction
