### ISSUE TITLE
Bug when plugin detached

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#3]
- Sometimes the application crash (need to be verified)
- Some functionalities don't work when detached (try connect to omeroDB)

**Comment by Akramhar** [comment]
Didn't happen to me while testing, if it doesn't happen anymore just close it

**Comment by strambc** [comment]
OMERO db connection works when detached
SPT plugins work when detached
Tracking Measures:
Intensity works when detached
Diffusivity OK
