### ISSUE TITLE
Diffusivity Measures: remaining issues

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#301]
Inherits from #272 and #266
# Run Tab
## Selector label: Log option --> ODC estimation method:

- [x] Maximum computation window size --> RESIZE STRING SIZE ON WINDOW (currently too short)
- [ ] Combo box items: only Log-log is visible, Linear and Linear and Log-log are missing.

# Results tables
## Moments of Displacement vs. delta t plots results
Missing columns
- [x] "Max Comp. Window Size" column is missing

Wrong Column LABELS -->
- [x] Moment's Order --> Moment's Order (Nu)
- [x] Moment of Displacement --> Moment of Displacement (Mu)

## Moment Scaling Spectrum results
Wrong Column LABELS -->
- [x] Slope Log-log MSD --> Slope (Gamma)
- [x] Intercept (y02) --> Intercept (y0)
- [x] Fits goodness --> Goodness of fit

# Phase space results
Wrong Column LABELS -->
- [x] Max Calculation Window --> Max Comp. Window Size

**Comment by Akramhar** [comment]
> Combo box items: only Log-log is visible, Linear and Linear and Log-log are missing.
Does this happen every time? Because I tried to reproduce and I'm not able atm.

**Comment by strambc** [comment]
Yes always

Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 17 Oct 2017, at 11:40, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Combo box items: only Log-log is visible, Linear and Linear and Log-log are missing.
Does this happen every time? Because I tried to reproduce and I'm not able atm.

**Comment by Akramhar** [comment]
Everything seems to be fixed, the only problem I can't track is

> Combo box items: only Log-log is visible, Linear and Linear and Log-log are missing.

We should open a specific issue because I'm not able to reproduce the problem.

**Comment by strambc** [comment]
Open new issue  --> #317 for
**Combo box items: only Log-log is visible, Linear and Linear and Log-log are missing.**
