### ISSUE TITLE
General: Run names on General data selector and SideBar selector + Data Browser

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#302]
Inherits #266 

# Run names on General data selector and SideBar selector + Data Browser

- [ ] - YYYY-MM-DD_XX-XX-XX_MOSAIC 2D SNR Estimation --> YYYY-MM-DD_XX-XX-XX_MOSAIC SE run
- [ ] - YYYY-MM-DD_XX-XX-XX_MOSAIC 2D Particle Detector --> YYYY-MM-DD_XX-XX-XX_MOSAIC 2D FPD run
- [ ] - YYYY-MM-DD_XX-XX-XX_MOSAIC 2D Particle Linking --> YYYY-MM-DD_XX-XX-XX_MOSAIC 2D FPT run
- [ ] - YYYY-MM-DD_XX-XX-XX_Default relinking run --> YYYY-MM-DD_XX-XX-XX_default OMEGA TE run
- [ ] - Unsaved relinking --> Unsaved Editing
- [ ] - YYYY-MM-DD_XX-XX-XX_Default segmentation run --> YYYY-MM-DD_XX-XX-XX_default OMEGA TS run
- [ ] - Unsaved segmentaion --> Unsaved Segmentation
- [ ] - YYYY-MM-DD_XX-XX-XX_Omega default intensity run --> YYYY-MM-DD_XX-XX-XX_default OMEGA IM run

** SAME FOR ALL OTHER Tracking Measures runs **

**Comment by Akramhar** [comment]
The name should be based on the name of the algorithm.
Since we updated algorithm names this should be changed too.
So this should be updated with omega-0.37

**Comment by Akramhar** [comment]
What's the problem here?

**Comment by Akramhar** [comment]
Moved to be tested in omega-0.38 with updated names, if there is still a problem this should be reviewed because I said the names are dependent on the algorithm names

**Comment by strambc** [comment]
@Akramhar The point is to use SHORTENED NAMES for the the comboboxes as indicated

**Comment by Akramhar** [comment]
this should be solved in omega-0.39
