### ISSUE TITLE
Default Tracking Measures runs missing

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#305]
1 image loaded
7 PD runs
1 PL run
Noticed that the in the Data Browser there are no Tracking measures runs.
Same is also true in the Tracking measures plugin.
____
CASE DESCRIPTION
Image VIRUS snr 7 density low_Trajectory 113.tif
7 PD runs --> 2/0.3/0.05 is the one that was further analyzed
1 PL --> 10/3/Brownian/1/1/G/10
TS run executed

**Comment by strambc** [comment]
@Akramhar

**Comment by Akramhar** [comment]
Even after some time?
Because I noticed that sometimes if I open a certain window before the automatic calculation have finished I dont see the results appearing.
I would have to click again on the selectors (in data browser click again on the segmentation for example)

**Comment by strambc** [comment]
Yes definitely.
Also after I run both IM and DM they do not appear.

**Comment by strambc** [comment]
@Akramhar might also be related --> when I try to switch between segmentation runs on the TS panel it does not refresh the window. Will open a different issue about this specifically -->#308

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/31675728-82596f6c-b333-11e7-81ef-befd2ccd4186.png)

**Comment by strambc** [comment]
@Akramhar launched the app again with only 1 image/1PD and 1PL and the issue reproduced as before --> NO TRACKING MEASURE RUNS ANYWHERE TO BE SEEN

**Comment by strambc** [comment]
## Step 2
1 image/1PD and 1PL /no TE/ TS run executed

DATA BROWSER --> NO TRACKING MEASURE RUNS ANYWHERE TO BE SEEN
OMEGA Intensity Measures --> OMEGA intensity Measures run available in combobox

**Comment by strambc** [comment]
Even in this case though the issue with the SEGMENTATION RUN REFRESH ON Tracking Measures TB persist --> switching the segmentation run on the combobox does not refresh the window

**Comment by Akramhar** [comment]
the "run missing in the data browser" seems to be fixed in omega 0.37
