### ISSUE TITLE
Trajectory Segmentation: after using the undo button segments do not get colored

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#306]
Same case as #305 
No color appears when segment is selected in Motion Type mode.
The bottom says: Current selection 10-26 Anomalous superdiffusion 
But no color appears.

__________
CASE DESCRIPTION
Image VIRUS snr 7 density low_Trajectory 113.tif
7 PD runs --> 2/0.3/0.05 is the one that was further analyzed
1 PL --> 10/3/Brownian/1/1/G/10

**Comment by strambc** [comment]
@Akramhar

**Comment by Akramhar** [comment]
Could you please elaborate more here.
I tried to run a test case, set motion type, select 2 spots --> it gets colored.
Undo --> gets black.
Redo --> gets colored.
Select same 2 spots with different segment Type --> gets colored with diff color.
Undo --> goes back to previous color.
Undo --> goes back to black.

Can't understand what is the erratic behaviour.

**Comment by strambc** [comment]
What happened was that when I would select the first point it would give me a guide line with the correct color.
When i then clicked on the second point it the interfaced behaved as if the selection had occurred, the bottom window said Segment so and so Motion type so and so as if everything was fine, except the color was unchanged and remained black.
When I hit UNDO ALL then it started working again.
This is what I observed

On Oct 17, 2017, at 14:56, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you please elaborate more here.
I tried to run a test case, set motion type, select 2 spots --> it gets colored.
Undo --> gets black.
Redo --> gets colored.
Select same 2 spots with different segment Type --> gets colored with diff color.
Undo --> goes back to previous color.
Undo --> goes back to black.

Can't understand what is the erratic behaviour.

**Comment by Akramhar** [comment]
I'll leave this open to see if we get more information because I'm not able to reproduce it

**Comment by Akramhar** [comment]
we should check if this happens again in omega-0.37

**Comment by strambc** [comment]
@Akramhar 
might be due to the issue we oberved yesterday with VIRUS snr 7 density low_Trajectory 113.tif and with  VIRUS snr 7 density low_Trajectory 33.tif

**Comment by strambc** [comment]
@Akramhar 
Testes with 375_1000.0_10.0_16_Bits_Grey_10_Horizontal_0.015_256_test1.ome.tif
PD --> default parameters
PL --> default parameters

**Behavior did not reproduce**

**Comment by strambc** [comment]
@Akramhar
Based on what reported above it is possible that previously observed behavior with TS color
might be due to the **UNDERLAYING CRASH behavior** we oberved yesterday with VIRUS snr 7 density low_Trajectory 113.tif and with VIRUS snr 7 density low_Trajectory 33.tif

**Comment by Akramhar** [comment]
I'll move this back to be tested with 0.38 since the crash problem seems to be solved in that version
