### ISSUE TITLE
Tracking Measures plots --> Symbols on plots do not match symbols on the legend

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#307]
In the Motion Type plots the symbols on the legend vs. the graph do not match.

__________
CASE DESCRIPTION
Image VIRUS snr 7 density low_Trajectory 113.tif
7 PD runs --> 2/0.3/0.05 is the one that was further analyzed
1 PL --> 10/3/Brownian/1/1/G/10

**Comment by Akramhar** [comment]
The only difference I can see is that there is one symbol (circle/ellipse) that I'm not able to draw correctly in the legend (usually the second one). I'm trying to find a solution for this.
Do you see other symbol that are not matching?

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/32197245-cf2a8a86-bd99-11e7-8267-67ca5b1f3d2c.png)

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/32197472-cdf14762-bd9a-11e7-9042-504dd6b339ba.png)

**Comment by Akramhar** [comment]
I have to investigate this further.

**Comment by Akramhar** [comment]
this should be solved in omega-0.41b
