### ISSUE TITLE
Trajectory segmetation plugin: switching between runs on the selector does not work

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#308]
Trajectory segmetation plugin: switching between runs on the selector does not refresh window.
Might be related to #305

**Comment by strambc** [comment]
Plots do not update as well.

**Comment by Akramhar** [comment]
Could you elaborate more on this please?
Which "plots" is not updated? What "window" is not refreshed?

**Comment by strambc** [comment]
Plots on the plot tab
Window on the Browser tab

Caterina Strambio De Castillia
Please excuse any spelling errors or short replies, this message was sent to you from my iPhone

On 17 Oct 2017, at 13:11, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you elaborate more on this please?
Which "plots" is not updated? What "window" is not refreshed?

**Comment by Akramhar** [comment]
So you mean that changing the selection on the TS plugin doesn't refresh the plots on TrackingMeasures plugins?

**Comment by Akramhar** [comment]
seems to be fixed in omega-0.37
