### ISSUE TITLE
Tracking measures --> a second Run will not work

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#309]
1 image (VIRUS snr 7 density low_Trajectory 113.tif)
1 PD run
1 PL run
No TE and no TS run
________
Run 1 Tracking Measures --> WORKED
Attempted to Run again --> BUTTON IS NOT AVAILABLE (Button gray)

**Comment by Akramhar** [comment]
Which Tracking Measures? The button should be grayed out until the previous run is finished, and then it should be available again.

**Comment by strambc** [comment]
It did not become available again.
I could not launch a new run again at all.
On Oct 17, 2017, at 16:08, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Which Tracking Measures? The button should be grayed out until the previous run is finished, and then it should be available again.

**Comment by Akramhar** [comment]
Which Tracking Measures were you trying to run when this happened?

**Comment by Akramhar** [comment]
should be checked again in omega-0.37

**Comment by Akramhar** [comment]
should be checked again in omega-0.37

**Comment by strambc** [comment]
It seems that with Diffusivity the issue is solved. 
Hower with Tracking Measures Intensity after a second run it appeared to crash.

**Comment by strambc** [comment]
Same behavior reproduced after the application was launched again.

Case Description
![image](https://user-images.githubusercontent.com/4050585/31970260-695f3c28-b8e5-11e7-8773-83a02923aecb.png)

**Comment by strambc** [comment]
Similar behavior again --> Omega Intensity Measures appeared to crash upon first Run attempt

## **Case description**
![image](https://user-images.githubusercontent.com/4050585/31970557-5f689af6-b8e6-11e7-828e-27544ad1fd6f.png)

**Comment by strambc** [comment]
-- Did not happen with Mobility Measures or with Velocity Measures
-- Did not happen with Diffusivity Measures with Error disabled

**Comment by strambc** [comment]
-- When attempting to run Diffusivity Measures with Error enabled 
--> Processing error analysis, trajectory Trak__0 1/61

[Log_core.log](https://github.com/OmegaProject/Omega/files/1412670/Log_core.log)

**Comment by strambc** [comment]
Confirmed that Intensity Measures gets stuck even when Use SNR Estimation is not checked.
Run does not even start.

![image](https://user-images.githubusercontent.com/4050585/31971161-96c062e8-b8e8-11e7-8925-bb8a129e364e.png)

**Comment by strambc** [comment]
@Akramhar 
this is what I am talking about

**Comment by Akramhar** [comment]
the intensity problem should be fixed in omega-0.38, the diffusivity problem needs to be checked again in omega-0.38 because I couldn't reproduce it.

**Comment by strambc** [comment]
@Akramhar did you take a look at the log?

**Comment by strambc** [comment]
This issue was closed and a new dedicated issue was opened #320
