### ISSUE TITLE
SidePanel sizes are messed up on mac

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#31]
At application launch SidePanel size is completely wrong.

**Comment by strambc** [comment]
Check this and decide whether to upgrade to HIGH depending on what the problem actually is.

**Comment by strambc** [comment]
Very annoying. 
Should be addressed.
Upgrade to HIGH

**Comment by Akramhar** [comment]
This may be fixed in omega-0.39.
Needs to be tested a lot before be sure that it has been fixed completely because its a tricky one.

**Comment by strambc** [comment]
Recent test done: repeated lunches.
Outcome: on average 1/35 the SideBar opens correctly
Look at RED TAB

[2017-11-01_DM_repeated.Runs.test_v05.xlsx](https://github.com/OmegaProject/Omega/files/1435570/2017-11-01_DM_repeated.Runs.test_v05.xlsx)
