### ISSUE TITLE
Export: add export all AVAILABLE button 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#310]
Currently   Export results only export the last selected analysis run
I think we should have an export all **AVAILABLE** button as well.
Another possible label could be **ACCESSIBLE**

**Button 1** with same functionality as now 
LABEL is Export results --> should be "Export last selected"

**Button 2** with ability to export all results down the tree that are AVAILABLE (have not been un-checked). To clarify: when one item is selected (blue highlight) all items downstream that are still "checked" have to be exported. Only those that have been un-checked will be left out from this export mode.
LABEL should be "Export all available"

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/31682053-ef6843b8-b346-11e7-9580-2871b7209614.png)

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/31682335-c3926a2e-b347-11e7-847a-f891a2752f1c.png)

**Comment by Akramhar** [comment]
this should be fixed in omega-0.37
