### ISSUE TITLE
Export issue --> general issues with export interface and output file

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#312]
# Issue 1
![image](https://user-images.githubusercontent.com/4050585/31683801-e5981bd8-b34b-11e7-91c9-cbe18d5aa073.png)

# Issue 2

![image](https://user-images.githubusercontent.com/4050585/31684005-871ce8bc-b34c-11e7-9d9c-3ecd16b33385.png)

If \t is used as separator this is what happens

![image](https://user-images.githubusercontent.com/4050585/31685553-5add2258-b351-11e7-9f37-e51f4ec33f0f.png)

**Comment by strambc** [comment]
# Issue 3
![image](https://user-images.githubusercontent.com/4050585/31684272-282b62f6-b34d-11e7-9a75-7cfb88e8129a.png)

**Comment by strambc** [comment]
# Issue 4
General header format --> USE SAME FORMAT AS results summary in each plugin + Algrorithm information

Example:

![image](https://user-images.githubusercontent.com/4050585/31685345-9f3c22a6-b350-11e7-9e61-f5bf44e87ee4.png)

**Comment by strambc** [comment]
# Issue 5
Particle ID is unclear.
What does it refer to?
This maybe fixed if PD plugin table is used as output format but I thought I would mention the issue
![image](https://user-images.githubusercontent.com/4050585/31686091-3b0b7ca2-b353-11e7-9125-3d0724ede8e6.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.37
