### ISSUE TITLE
Diffusivity Measures --> ODC estimation method options not available

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#313]
Inherits from #301
# Run Tab
## Selector label: Log option --> ODC estimation method:

- [ ] Combo box items: only Log-log is visible, Linear and Linear and Log-log are missing.

**Comment by Akramhar** [comment]
Needs to be tested in omega-0.37 to see if still happening

**Comment by strambc** [comment]
v037b
issue is still there, however now the option visible is "log and linear"
