### ISSUE TITLE
OMEGATrackinMeasures: trajectories that are unselected on the TB show up in Side Bar

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#314]
Inherits in part to  #249
New issue created because now when a trajectory is de-selected on a browser the segment continue showing on the SIDE BAR overlay.

What disappears is the BOUNDING BOX. However the segment itself is still showing.
Same thing applies with Edited Trajectories overlay and to the Trajectories overaly.

**Comment by strambc** [comment]
![issue 314_step 1](https://user-images.githubusercontent.com/4050585/31963288-2875e4f8-b8ce-11e7-8d25-d5fa70cef4a5.png)
![issue 314_step 2](https://user-images.githubusercontent.com/4050585/31963289-288966d6-b8ce-11e7-8603-156e49685e48.png)
![issue 314_step 3](https://user-images.githubusercontent.com/4050585/31963290-289d4a2a-b8ce-11e7-9a0b-e8a6a5a4f38b.png)
![issue 314_step 4](https://user-images.githubusercontent.com/4050585/31963291-28b00a66-b8ce-11e7-852c-24260748eeba.png)
![issue 314_step 5](https://user-images.githubusercontent.com/4050585/31963292-28bd52f2-b8ce-11e7-9fc9-51789960c076.png)

**Comment by Akramhar** [comment]
These browser you posted are Tracking Measures, so we are talking about segments not trajectories. Am I correct?

**Comment by Akramhar** [comment]
Segments are correctly hidden when unchecked in omega-0.38

**Comment by strambc** [comment]
New issue opened that inherits from this one #325
