### ISSUE TITLE
Trackin Measures_Diffusivity_Run Tab Combo box: only Linear and Log-log visible

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#317]
Inherits from #301 

# Run Tab
## Selector label: Log option --> ODC estimation method:
- [ ] Combo box items: only "**Linear and Log-log**" is now visible both Log-log and, Linear are not visible

**Comment by strambc** [comment]
Same as #313

**Comment by Akramhar** [comment]
should be fixed in omega-0.38, need to be tested a lot

**Comment by strambc** [comment]
MUCH MORE INVESTIGATION ON THIS TOPIC recorded in the attached spreadsheet
[2017-10-26_DM_repeated Runs test.xlsx](https://github.com/OmegaProject/Omega/files/1416415/2017-10-26_DM_repeated.Runs.test.xlsx)

**Comment by strambc** [comment]
Opened a new dedicated issue connected to this one.
#320
