### ISSUE TITLE
Diffusivity Measures: issues related with crash connected with Run

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#320]
Inherits from #317 

- First observation : often (but not always) the "ODC estimation method combox" in the Run tab of the DM plugin does not display the three options but only the central one: "Linear and Log-log".

- Second observation: this behaviors occurs only with certain combinations of events. For example it appears to be connected with the image that is used. It is certainly associated with the Trajectory_113 and Trajectory_33 images but less with other images.

- Third observation: the behavior can appear during a specific OMEGA session (see attached Excel spreadsheet) and appears to be connected with an underlayin crash. However in some cases it apears as if the application can continue working at some level.

- Forth observation: a systematic study of behaviors was conducted and detailed in the attached spreadsheet

[2017-10-26_DM_repeated Runs test.xlsx](https://github.com/OmegaProject/Omega/files/1419242/2017-10-26_DM_repeated.Runs.test.xlsx)

**Comment by strambc** [comment]
Testing will resume with version 038

**Comment by strambc** [comment]
Might be connected with #306

**Comment by Akramhar** [comment]
moved to be tested for omega-0.38

**Comment by strambc** [comment]
@Akramhar 
Repeated Run issue appears to be gone.
However COMBOBOX still same issue.
WILL REDO EXCEL SPREADSHEET SYSTEMATIC TEST ON MONDAY

**Comment by strambc** [comment]
#330
