### ISSUE TITLE
SideBar: 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#322]
Inherits #290
When un-checking backwards Segmentd Trajecrtories remain selected on "Select Overaly to Display" and does not match with what is checked on DB.
While correct behavior should be that SB follows check-marks on Side Bar (see issue #321)

It appears to me that in the case in which this is not the case it is not clear why SB shows Particles and not NOTHING AT ALL. It should go back to NONE.
Why does it go back to only available overlay?

![issue 290_problem_3_step_1](https://user-images.githubusercontent.com/4050585/31521136-65ca3248-af76-11e7-8d78-3267a3a4ee41.png)
![issue 290_problem_3_step_2](https://user-images.githubusercontent.com/4050585/31521137-65e27812-af76-11e7-846a-19f9bdfe9c68.png)

**Comment by Akramhar** [comment]
Like I said in #294 there is a limitation, the selection of what is displayed can only go up at the present time.
To make it go down too a discrete amount of changes is necessary.
This should be a possible new feature for 2.0

**Comment by Akramhar** [comment]
I think there is already a issue about this in Beta 2.0.
One should be closed.
