### ISSUE TITLE
General: change default trajectory color

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#323]
Change default trajectory/segment color to HEX 999999 Color Hex Gray60
This is important becaues one of the SEGMENTATION colors is the same as the default trajectory color.

**Comment by Akramhar** [comment]
this should be fixed in omega-0.38

**Comment by strambc** [comment]
@Akramhar thank you.
I had to change the color as I realized that the color I had selected  was great on the black image background but is not really visible on the graphs.

**Comment by Akramhar** [comment]
So which one it should be now ?

**Comment by strambc** [comment]
@Akramhar the color is the GRAY color indcated above and again here:
HEX 999999 Color Hex Gray60

**Comment by Akramhar** [comment]
fixed in omega-0.39
