### ISSUE TITLE
Importer: missing required distinction when launched

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#328]
Atm the importer requires to know if is importing particles or tracks.
On the same window or one that would appear before, a selection must be made in order to import the correct type of data.

**Comment by Akramhar** [comment]
this should be fixed in omega-0.39

**Comment by strambc** [comment]
@Akramhar waiting to test for importer/exporter overhaul

**Comment by strambc** [comment]
I am pretty sure this is taken care of because the Importer window requires the user to select the Import type.
