### ISSUE TITLE
v039b: bounding box for Segments on SideBar appears and disappears

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#340]
When segmented trajectory (full trajectory is a single segment; segment is short) is selected on DTM the bounding box appears very very briefly (flickers) and then disappears

![image](https://user-images.githubusercontent.com/4050585/32338323-c4e40826-bfca-11e7-92b4-4da3b9fceb71.png)

**Comment by Akramhar** [comment]
this is related with #337, #338 & #339.
They should all be fixed in omega-0.40
