### ISSUE TITLE
v040: Diffusivity run on Segmented Trajectory does not execute

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#341]
![image](https://user-images.githubusercontent.com/4050585/32346839-1f775a62-bfe5-11e7-927d-18019ec7e5bc.png)

**Comment by strambc** [comment]
Note --> Track_22_24-27 is 4 particles long.
There is a warning.
As a consequence the Run gets stopped.

**Comment by strambc** [comment]
In addition observed following behavior:
Segment 1-24 which is empty and overlaps with three additional segments that are as follows:
-- 16-24
-- 24-27
-- 27-35

![image](https://user-images.githubusercontent.com/4050585/32347103-f9f3fbb4-bfe5-11e7-8a45-aea77498f942.png)

**Comment by strambc** [comment]
@Akramhar

**Comment by strambc** [comment]
Same issue:
the trajectory underwent some do and un-do during segmentation and the outcome was the existance of overlapping segments:

![image](https://user-images.githubusercontent.com/4050585/32351060-96d6ac86-bff2-11e7-8eaa-f9a812da5b48.png)

**Comment by Akramhar** [comment]
the problem that the "error enabled" run stops should be solved in omega-0.41c

**Comment by Akramhar** [comment]
the problem of the empty segments could not be reproduced, if it happens again a specific problem for that should be opened
