### ISSUE TITLE
v040: SideBar does not show image details after PD run

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#342]
## Behavior 1 --> After PD
![2017-11-08_issue 342_step1](https://user-images.githubusercontent.com/4050585/32558550-0451e85a-c473-11e7-9349-c90079220b65.png)

**Comment by strambc** [comment]
## Behavior 2 --> After PL
![2017-11-08_issue 342_step2](https://user-images.githubusercontent.com/4050585/32558518-f02ee5c6-c472-11e7-9b64-9be9876e046c.png)

**Comment by Akramhar** [comment]
should be fixed in omega-0.40
