### ISSUE TITLE
OMEGA export: add IMAGE name as a suffix for alla file names

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#344]
Add the name of the image as a HARD CODED suffix for all file names
Example:
VIRUS snr 7 density low_tSr.tif_2018-03-06_04-33-53_OMEGA DM_phaseSpace.txt

![screen shot 2018-03-06 at 17 19 05](https://user-images.githubusercontent.com/4050585/37061806-98182c10-2162-11e8-8859-7741e55e8c6c.png)

**Comment by Akramhar** [comment]
should be fixed in omega 0.44

**Comment by Akramhar** [comment]
prefixes are now an option in the exporter in both cases (for single run and all runs)
