### ISSUE TITLE
OMEGA export: error in OMEGA DM_phaseSpace text file

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#345]
Export file OMEGA DM_phaseSpace.txt

Column Headers

Segment   Name | Motion Type | Segment Length
are inserted by mistake in the place of the correct
Max Computation Window Size

See screeb shot

![screen shot 2018-03-06 at 17 22 50](https://user-images.githubusercontent.com/4050585/37061941-0c231c28-2163-11e8-945f-4fb109a6b263.png)

**Comment by Akramhar** [comment]
should be fixed in omega 0.44
