### ISSUE TITLE
 OMEGA export: possibility to create folders while exporting

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#348]
One of the exporting issue is that there is no direct connection between files.
Add a feature in the exporter that allow to generate folders similar to the analysis run structure in the model.
Add the "parents" of a run at the beginning of the metadata.

**Comment by Akramhar** [comment]
should be working in omega 0.44

**Comment by strambc** [comment]
Issues with creating folders during export

- Works well in the following cases:

1. When image is selected

- - Folder is created with the name of the image
- - Structure is ok

2. When FPD is selected
- - Folder is created with the name of the image with correct structure
- - additional "null" folder is created where the FPD results are stored

3. When FPT is selected
- - Folder is created with the name of the image with correct structure
- - additional "null" folder is created where the FPD and FPT results are stored

Same pattern continues down the chain.

4. When one of the specific TM run is selected
- - "null" folder is created where all slected results are stored (only results pertaining to the selected TM run are exported).
