### ISSUE TITLE
ParticleLinking Mosaic "Min track length" param NOT APPLIED

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#46]
1. The parameter is not applied.
2. It is enabled when relaunching previous run but the value entered is not transferred to the queue.
   Has to check whether this applies also to SPT DLL

**Comment by strambc** [comment]
Check if this issue also applies to SPT DLL linking

**Comment by Akramhar** [comment]
Seems to be working now, to be verified
