### ISSUE TITLE
TrackSegment button names

### ISSUE THREAD

**Issue by Akramhar** [OmegaProject/Omega#60]
Apply -> Save
Cancel -> Undo all

**Comment by Akramhar** [comment]
Should be fixed in omega-0.34

**Comment by strambc** [comment]
Cancel was changed to Cancel all and not to Undo all as requested
Please change Cancel all --> Undo all

**Comment by Akramhar** [comment]
should be fixed in omega-0.35

**Comment by strambc** [comment]
Problem solved
