### ISSUE TITLE
OmeroBrowser check if image name is fully visible at least in list mode

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#77]
This has probably been fixed already.
Check if the issue persist.

**Comment by strambc** [comment]
Has to check whether the issue persist.

**Comment by strambc** [comment]
Image name is not fully visible if more than 50 character.
There is no way of being able to see it all unless the image is loaded.
A solution has to be found.
Resizing column width is definitely a possible solution #27
A quick fix might be a mouse-over label.

**Comment by Akramhar** [comment]
should be resolved with the jlist and jtable components for grid and list view.
plus there are now tooltips on the image in each view
