### ISSUE TITLE
General ID set to -1 when image not in DB

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#81]
ID is set to -1 when the image has not been saved to DB yet.
Should be "-" or "nd" or something more significant.

**Comment by Akramhar** [comment]
Should be changed to general ID instead of Image ID because this behavior is standard for every element in the system atm.
Every ID is initialized to -1 and showed as is. Should be changed that every ID that is -1 is displayed as something else ("-" or "n.d.")
