### ISSUE TITLE
OmegaMain Edit>Update Trajectories gets stuck when launched

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#87]
Upon launch, when one selects the Edit>Update Trajectories submenu, a "Updating analysis Omega server" window appears (see screen shot) which is non-responsive, cannot be closed, either with the "Close" button or with the "red" corner button.
However application appears to maintain responsiveness (e.g. open plugins launcher windows, selecting Edit>Database Preferences, continue to work).

**Comment by strambc** [comment]
Applies to both Mac and Win

**Comment by Akramhar** [comment]
Update trajectories doesn't exists anymore.
