### ISSUE TITLE
OmegaMain menu items and dependent windows rename

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#88]
The following OmegaMain menu items and dependent windows have to be renamed as follows:
1. File>"Import tracks" -> "Import Trajectories"
2. File>"Import tracks">>Mouse-over label = "Import tracks results from file" -> "Import trajectory results from file"
   File>"Import tracks">>Window title = "Omega Tracks Target Selector" -> "Select files containing trajectories to import in Omega DB" [IS THIS CORRECT? THIS WINDOW IS NOT CLEAR] 
   See also: #89
   When it is clarified make similar changes to the dependent window titles of all File>Import/Export submenues.
3. File>"Export tracks" -> "Export Trajectories"
4. File>"Export tracks">>Mouse-over label = "Export tracks results to file" -> "Export trajectory results to file"
5. File>"Export diffusivity results" -> "Export Diffusivity Results" [WHY ONLY DIFFUSIVITY?]
6. File>"Export all data" -> "Export all data" -> "Export All Results"
7. File>"Export all data" >>Mouse-over label = "Export all data results to file" -> "Export all results to file"
8. File>Load>>Window title = "Loading analysis from Omega server" -> "Loading analysis results from Omega DB"
9. File>Load orphaned>>Window title = "Loading analysis from Omega server" -> "Loading orphaned analysis results from Omega DB"
10. File>Save>>Window title = "Saving analysis to Omega server" -> "Saving analysis results to Omega DB"
11. Edit>Update Trajectories>>Window title = "Updating analysis in Omega server" -> "Updating analysis results in Omega DB"

**Comment by Akramhar** [comment]
This issues is outdated, most of this stuff have been renamed / removed / changed.
