### ISSUE TITLE
OmegaMain File>Import/Export submenues window functionality not clear

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#89]
This applies to: File> Import tracks, Export tracks, Export diffusivity results, Export all data.

It is not clear what to do with the first window.
Is one supposed to select the files containing trajectories to be imported?
Is one supposed to select the images to which the trajectories will be assigned?

What does the "Next" button do?

Very unfriendly.
Labels have to be changed but not clear how since the functionality is not clear

**Comment by strambc** [comment]
Applies to both Mac and Win

**Comment by strambc** [comment]
Talk with Alex about:

1) expected functionality
2) interface improvement

**Comment by Akramhar** [comment]
The menu has been completely removed, the functionality has been moved in omegabrowser
