### ISSUE TITLE
SNREstimation plungin functionality is not clear

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#96]
Not clear how this plugin works.
When image is selected using the "Select Image" pull-down menu, nothing appears in the Loaded Data window. 
Run Queue is empty.
The add to queue button is not active.
What is the expected functinality?

**Comment by strambc** [comment]
Applies to both Mac and Win

**Comment by Akramhar** [comment]
what do you mean is not clear?
You select an image:
- if the image doesn't contains any particleDetection results -> the list is empty
- if the image contains at least 1 particleDetection results -> you can see it in the list and process it to obtain a SNR results
