### ISSUE TITLE
Omega edit plugin/algorithm descriptions

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#99]
Edit algorithm and plugin information and description as indicated in the text files found at the attached link:

https://www.dropbox.com/sh/rla9nkjw0f2r8ac/AAAr2AiroLCXPBx5AjJ2Qlfza?dl=0

**Comment by strambc** [comment]
CHECK WHAT IS THE CURRENT STATUS and if more descriptions have to be added

**Comment by Akramhar** [comment]
Everything in the folder ATM as been up updated in omega-0.34.
I'll close this issue and if new things need to be added, we open a new issue

**Comment by strambc** [comment]
This issue was closed and remaining issues transferred to #263
